/** User-facing chrome strings, one set per site language. */
export type Strings = typeof EN;

export const EN = {
  lang: "en",
  dirDocs: "Guide",
  navGuide: "Guide",
  navInstall: "Install",
  navDownload: "Download",
  navChangelog: "Changelog",
  navDesign: "Design",
  searchPlaceholder: "Search the guide  /",
  searchEmpty: "No results. Try another search term.",
  tocTitle: "On this page",
  prev: "Previous page",
  next: "Next page",
  editPage: "Read the source on GitHub",
  skipToContent: "Skip to content",
  toggleTheme: "Toggle theme",
  toggleNav: "Open menu",
  footerBlurb: "A GPU-accelerated terminal where you and your AI agents work together.",
  footerDocs: "Guide",
  footerProject: "Project",
  footerReleases: "Releases",
  footerIssues: "Issues",
  footerKeybindings: "Keyboard shortcuts",
  footerPlugins: "Plugins",
  footerNote: "MIT licensed",
  untranslated: "This page is not available in English yet. You can read the Korean original below.",
  stale: "The Korean page has been updated. Check the source for changes that are not yet included in this translation.",
  translateCta: "Read the Korean source",
};

export const KO: Strings = {
  lang: "ko",
  dirDocs: "가이드",
  navGuide: "가이드",
  navInstall: "설치",
  navDownload: "다운로드",
  navChangelog: "변경 이력",
  navDesign: "디자인",
  searchPlaceholder: "가이드 검색  /",
  searchEmpty: "검색 결과가 없습니다. 다른 검색어로 찾아보세요.",
  tocTitle: "이 페이지에서",
  prev: "이전 페이지",
  next: "다음 페이지",
  editPage: "GitHub에서 원문 보기",
  skipToContent: "본문으로 건너뛰기",
  toggleTheme: "테마 전환",
  toggleNav: "메뉴 열기",
  footerBlurb: "나와 AI 에이전트가 함께 일하는 GPU 가속 터미널.",
  footerDocs: "가이드",
  footerProject: "프로젝트",
  footerReleases: "릴리스",
  footerIssues: "이슈",
  footerKeybindings: "단축키",
  footerPlugins: "플러그인",
  footerNote: "MIT 라이선스",
  untranslated: "아직 영어 번역을 준비하지 못했습니다. 우선 한국어 원문을 참고해 주세요.",
  stale: "한국어 원문이 업데이트되어 번역과 내용이 다를 수 있습니다. 최신 내용은 원문을 확인해 주세요.",
  translateCta: "한국어 원문 보기",
};

export const stringsFor = (lang: "ko" | "en") => (lang === "ko" ? KO : EN);
