/** User-facing chrome strings, one set per site language. */
export type Strings = typeof EN;

export const EN = {
  lang: "en",
  dirDocs: "Guide",
  navGuide: "Guide",
  navInstall: "Install",
  navDownload: "Download",
  navChangelog: "Changelog",
  navDesign: "Design",
  searchPlaceholder: "Search the guide  /",
  searchEmpty: "No results",
  tocTitle: "On this page",
  prev: "Previous",
  next: "Next",
  editPage: "View this page on GitHub",
  skipToContent: "Skip to content",
  toggleTheme: "Toggle theme",
  toggleNav: "Open navigation",
  footerBlurb: "A GPU-accelerated terminal where you and your AI agents work together.",
  footerDocs: "Guide",
  footerProject: "Project",
  footerReleases: "Releases",
  footerIssues: "Issues",
  footerKeybindings: "Keyboard shortcuts",
  footerPlugins: "Plugins",
  footerNote: "MIT licensed",
  untranslated: "This page has not been translated yet — showing the Korean original.",
  stale: "This translation is older than the Korean source and may be out of date.",
  translateCta: "View the source",
};

export const KO: Strings = {
  lang: "ko",
  dirDocs: "가이드",
  navGuide: "가이드",
  navInstall: "설치",
  navDownload: "다운로드",
  navChangelog: "변경 이력",
  navDesign: "디자인",
  searchPlaceholder: "가이드 검색  /",
  searchEmpty: "검색 결과가 없습니다",
  tocTitle: "이 페이지",
  prev: "이전",
  next: "다음",
  editPage: "GitHub 에서 이 문서 보기",
  skipToContent: "본문으로 건너뛰기",
  toggleTheme: "테마 전환",
  toggleNav: "탐색 열기",
  footerBlurb: "나와 AI 에이전트가 함께 일하는 GPU 가속 터미널.",
  footerDocs: "가이드",
  footerProject: "프로젝트",
  footerReleases: "릴리스",
  footerIssues: "이슈",
  footerKeybindings: "단축키",
  footerPlugins: "플러그인",
  footerNote: "MIT 라이선스",
  untranslated: "이 문서는 아직 번역되지 않았습니다. 한국어 원문을 표시합니다.",
  stale: "이 번역은 한국어 원문보다 오래됐습니다. 내용이 다를 수 있습니다.",
  translateCta: "원문 보기",
};

export const stringsFor = (lang: "ko" | "en") => (lang === "ko" ? KO : EN);
