//! `KeybindingSettings` — preset 정의 (tasty / mac / windows / linux).

use super::KeybindingSettings;

impl KeybindingSettings {
    /// Tasty preset (default). All platform copy/paste/zoom bindings combined.
    pub fn preset_tasty() -> Self {
        Self {
            new_workspace: vec!["alt+n".into()],
            new_tab: vec!["alt+t".into()],
            split_pane_vertical: vec!["alt+e".into()],
            split_pane_horizontal: vec!["alt+shift+e".into()],
            split_surface_vertical: vec!["alt+d".into()],
            split_surface_horizontal: vec!["alt+shift+d".into()],
            toggle_settings: vec!["ctrl+,".into()],
            toggle_notifications: vec!["ctrl+shift+i".into()],
            toggle_dag_list: vec!["ctrl+shift+g".into()],
            close_pane: vec!["ctrl+shift+w".into()],
            close_surface: vec!["alt+w".into()],
            close_workspace: vec!["alt+shift+w".into()],
            focus_pane_next: vec!["ctrl+]".into()],
            focus_pane_prev: vec!["ctrl+[".into()],
            focus_surface_next: vec!["alt+]".into()],
            focus_surface_prev: vec!["alt+[".into()],
            tab_switch_modifier: "ctrl".to_string(),
            workspace_switch_modifier: "alt".to_string(),
            category_switch_modifier: "ctrl+shift".to_string(),
            toggle_sidebar: vec!["ctrl+shift+b".into()],
            toggle_sidebar_collapse: vec!["ctrl+b".into()],
            toggle_categories_collapsed: vec![],
            restore_closed: vec!["ctrl+shift+t".into()],
            screenshot_to_clipboard: vec!["ctrl+alt+s".into()],
            quit: Vec::new(),
            quit_immediate: Vec::new(),
            quit_minimize: Vec::new(),
            open_markdown: Vec::new(),
            open_explorer: Vec::new(),
            convert_surface: vec!["alt+'".into()],
            convert_to_markdown: Vec::new(),
            convert_to_explorer: Vec::new(),
            new_window: vec!["alt+shift+n".into()],
            close_active: vec!["ctrl+w".into()],
            next_tab: Vec::new(),
            prev_tab: Vec::new(),
            find: vec!["ctrl+f".into(), "alt+f".into()],
            copy: vec!["ctrl+c".into(), "alt+c".into(), "ctrl+shift+c".into()],
            copy_path: vec!["alt+shift+c".into()],
            cut: vec!["ctrl+x".into(), "alt+x".into()],
            select_all: vec!["ctrl+a".into(), "alt+a".into()],
            explorer_refresh: vec!["f5".into()],
            explorer_go_up: vec!["alt+up".into()],
            paste: vec!["ctrl+v".into(), "alt+v".into(), "ctrl+shift+v".into()],
            zoom_in: vec![
                "ctrl+=".into(),
                "ctrl++".into(),
                "alt+=".into(),
                "alt++".into(),
            ],
            zoom_out: vec!["ctrl+-".into(), "alt+-".into()],
            zoom_reset: vec!["ctrl+0".into(), "alt+0".into()],
            rename_tab: vec!["f2".into()],
            rename_workspace: vec!["f3".into()],
            rename_workspace_subtitle: vec!["f4".into()],
            image_undo: vec!["ctrl+z".into(), "alt+z".into()],
            image_redo: vec!["ctrl+shift+z".into(), "alt+shift+z".into()],
            toggle_command_palette: vec!["ctrl+shift+p".into(), "alt+shift+p".into()],
            apply_workspace_preset: Vec::new(),
            apply_tab_preset: Vec::new(),
            apply_pane_preset: Vec::new(),
            enter_copy_mode: vec!["ctrl+shift+space".into()],
            minimize_window: Vec::new(),
            maximize_window: Vec::new(),
            close_window: Vec::new(),
            script_bindings: Vec::new(),
            // quick-switch raw 키. 4 프리셋 모두 tab/workspace modifier 기본값이
            // ctrl/alt 로 동일하므로 vim 스타일 키(l/h/j/k)를 공통 적용한다.
            tab_switch_slot_keys: super::default_tab_slot_keys(),
            workspace_switch_slot_keys: super::default_workspace_slot_keys(),
            category_switch_slot_keys: super::default_category_slot_keys(),
            tab_switch_next_key: super::default_tab_next_key(),
            tab_switch_prev_key: super::default_tab_prev_key(),
            workspace_switch_next_key: super::default_workspace_next_key(),
            workspace_switch_prev_key: super::default_workspace_prev_key(),
            category_switch_next_key: super::default_category_next_key(),
            category_switch_prev_key: super::default_category_prev_key(),
        }
    }

    /// Mac preset. ⌘ (alt) centric, following iTerm2 / Terminal.app conventions.
    pub fn preset_mac() -> Self {
        Self {
            new_workspace: vec!["alt+n".into()],
            new_tab: vec!["alt+t".into()],
            split_pane_vertical: vec!["alt+e".into()],
            split_pane_horizontal: vec!["alt+shift+e".into()],
            split_surface_vertical: vec!["alt+d".into()],
            split_surface_horizontal: vec!["alt+shift+d".into()],
            toggle_settings: vec!["alt+,".into()],
            toggle_notifications: vec!["alt+shift+i".into()],
            toggle_dag_list: vec!["alt+shift+g".into()],
            close_pane: vec!["alt+shift+w".into()],
            close_surface: vec!["alt+w".into()],
            close_workspace: Vec::new(),
            focus_pane_next: vec!["ctrl+]".into()],
            focus_pane_prev: vec!["ctrl+[".into()],
            focus_surface_next: vec!["alt+]".into()],
            focus_surface_prev: vec!["alt+[".into()],
            tab_switch_modifier: "ctrl".to_string(),
            workspace_switch_modifier: "alt".to_string(),
            category_switch_modifier: "ctrl+shift".to_string(),
            toggle_sidebar: vec!["alt+shift+b".into()],
            toggle_sidebar_collapse: vec!["alt+b".into()],
            toggle_categories_collapsed: vec![],
            restore_closed: vec!["ctrl+shift+t".into()],
            screenshot_to_clipboard: vec!["ctrl+alt+s".into()],
            quit: vec!["alt+q".into()],
            quit_immediate: Vec::new(),
            quit_minimize: vec!["alt+m".into()],
            open_markdown: Vec::new(),
            open_explorer: Vec::new(),
            convert_surface: vec!["alt+'".into()],
            convert_to_markdown: Vec::new(),
            convert_to_explorer: Vec::new(),
            new_window: vec!["alt+shift+n".into()],
            close_active: Vec::new(),
            next_tab: Vec::new(),
            prev_tab: Vec::new(),
            find: vec!["alt+f".into()],
            copy: vec!["alt+c".into()],
            copy_path: vec!["alt+shift+c".into()],
            cut: vec!["alt+x".into()],
            select_all: vec!["alt+a".into()],
            explorer_refresh: vec!["f5".into()],
            explorer_go_up: vec!["alt+up".into()],
            paste: vec!["alt+v".into()],
            zoom_in: vec!["alt+=".into(), "alt++".into()],
            zoom_out: vec!["alt+-".into()],
            zoom_reset: vec!["alt+0".into()],
            rename_tab: vec!["f2".into()],
            rename_workspace: vec!["f3".into()],
            rename_workspace_subtitle: vec!["f4".into()],
            image_undo: vec!["alt+z".into()],
            image_redo: vec!["alt+shift+z".into()],
            toggle_command_palette: vec!["alt+shift+p".into()],
            apply_workspace_preset: Vec::new(),
            apply_tab_preset: Vec::new(),
            apply_pane_preset: Vec::new(),
            enter_copy_mode: vec!["ctrl+shift+space".into()],
            minimize_window: Vec::new(),
            maximize_window: Vec::new(),
            close_window: Vec::new(),
            script_bindings: Vec::new(),
            // quick-switch raw 키. 4 프리셋 모두 tab/workspace modifier 기본값이
            // ctrl/alt 로 동일하므로 vim 스타일 키(l/h/j/k)를 공통 적용한다.
            tab_switch_slot_keys: super::default_tab_slot_keys(),
            workspace_switch_slot_keys: super::default_workspace_slot_keys(),
            category_switch_slot_keys: super::default_category_slot_keys(),
            tab_switch_next_key: super::default_tab_next_key(),
            tab_switch_prev_key: super::default_tab_prev_key(),
            workspace_switch_next_key: super::default_workspace_next_key(),
            workspace_switch_prev_key: super::default_workspace_prev_key(),
            category_switch_next_key: super::default_category_next_key(),
            category_switch_prev_key: super::default_category_prev_key(),
        }
    }

    /// Windows preset. Ctrl+Shift centric, following Windows Terminal conventions.
    pub fn preset_windows() -> Self {
        Self {
            new_workspace: vec!["alt+n".into()],
            new_tab: vec!["alt+t".into()],
            split_pane_vertical: vec!["alt+shift+e".into()],
            split_pane_horizontal: vec!["alt+shift+d".into()],
            split_surface_vertical: vec!["alt+d".into()],
            split_surface_horizontal: vec!["alt+e".into()],
            toggle_settings: vec!["ctrl+,".into()],
            toggle_notifications: vec!["ctrl+shift+i".into()],
            toggle_dag_list: vec!["ctrl+shift+g".into()],
            close_pane: vec!["ctrl+shift+w".into()],
            close_surface: vec!["alt+w".into()],
            close_workspace: vec!["alt+shift+w".into()],
            focus_pane_next: vec!["ctrl+]".into()],
            focus_pane_prev: vec!["ctrl+[".into()],
            focus_surface_next: vec!["alt+]".into()],
            focus_surface_prev: vec!["alt+[".into()],
            tab_switch_modifier: "ctrl".to_string(),
            workspace_switch_modifier: "alt".to_string(),
            category_switch_modifier: "ctrl+shift".to_string(),
            toggle_sidebar: vec!["ctrl+shift+b".into()],
            toggle_sidebar_collapse: vec!["ctrl+b".into()],
            toggle_categories_collapsed: vec![],
            restore_closed: vec!["ctrl+shift+t".into()],
            screenshot_to_clipboard: vec!["ctrl+alt+s".into()],
            quit: Vec::new(),
            quit_immediate: Vec::new(),
            quit_minimize: Vec::new(),
            open_markdown: Vec::new(),
            open_explorer: Vec::new(),
            convert_surface: vec!["alt+'".into()],
            convert_to_markdown: Vec::new(),
            convert_to_explorer: Vec::new(),
            new_window: vec!["ctrl+shift+n".into()],
            close_active: vec!["ctrl+w".into()],
            next_tab: Vec::new(),
            prev_tab: Vec::new(),
            find: vec!["ctrl+f".into()],
            copy: vec!["ctrl+c".into()],
            copy_path: vec!["alt+shift+c".into()],
            cut: vec!["ctrl+x".into()],
            select_all: vec!["ctrl+a".into()],
            explorer_refresh: vec!["f5".into()],
            explorer_go_up: vec!["alt+up".into()],
            paste: vec!["ctrl+v".into()],
            zoom_in: vec!["ctrl+=".into(), "ctrl++".into()],
            zoom_out: vec!["ctrl+-".into()],
            zoom_reset: vec!["ctrl+0".into()],
            rename_tab: vec!["f2".into()],
            rename_workspace: vec!["f3".into()],
            rename_workspace_subtitle: vec!["f4".into()],
            image_undo: vec!["ctrl+z".into()],
            image_redo: vec!["ctrl+shift+z".into()],
            toggle_command_palette: vec!["ctrl+shift+p".into()],
            apply_workspace_preset: Vec::new(),
            apply_tab_preset: Vec::new(),
            apply_pane_preset: Vec::new(),
            enter_copy_mode: vec!["ctrl+shift+space".into()],
            minimize_window: Vec::new(),
            maximize_window: Vec::new(),
            close_window: Vec::new(),
            script_bindings: Vec::new(),
            // quick-switch raw 키. 4 프리셋 모두 tab/workspace modifier 기본값이
            // ctrl/alt 로 동일하므로 vim 스타일 키(l/h/j/k)를 공통 적용한다.
            tab_switch_slot_keys: super::default_tab_slot_keys(),
            workspace_switch_slot_keys: super::default_workspace_slot_keys(),
            category_switch_slot_keys: super::default_category_slot_keys(),
            tab_switch_next_key: super::default_tab_next_key(),
            tab_switch_prev_key: super::default_tab_prev_key(),
            workspace_switch_next_key: super::default_workspace_next_key(),
            workspace_switch_prev_key: super::default_workspace_prev_key(),
            category_switch_next_key: super::default_category_next_key(),
            category_switch_prev_key: super::default_category_prev_key(),
        }
    }

    /// Linux preset. Ctrl+Shift centric, following GNOME Terminal conventions.
    pub fn preset_linux() -> Self {
        Self {
            new_workspace: vec!["alt+n".into()],
            new_tab: vec!["alt+t".into()],
            split_pane_vertical: vec!["alt+shift+e".into()],
            split_pane_horizontal: vec!["alt+shift+d".into()],
            split_surface_vertical: vec!["alt+d".into()],
            split_surface_horizontal: vec!["alt+e".into()],
            toggle_settings: vec!["ctrl+,".into()],
            toggle_notifications: vec!["ctrl+shift+i".into()],
            toggle_dag_list: vec!["ctrl+shift+g".into()],
            close_pane: vec!["ctrl+shift+w".into()],
            close_surface: vec!["alt+w".into()],
            close_workspace: vec!["alt+shift+w".into()],
            focus_pane_next: vec!["ctrl+]".into()],
            focus_pane_prev: vec!["ctrl+[".into()],
            focus_surface_next: vec!["alt+]".into()],
            focus_surface_prev: vec!["alt+[".into()],
            tab_switch_modifier: "ctrl".to_string(),
            workspace_switch_modifier: "alt".to_string(),
            category_switch_modifier: "ctrl+shift".to_string(),
            toggle_sidebar: vec!["ctrl+shift+b".into()],
            toggle_sidebar_collapse: vec!["ctrl+b".into()],
            toggle_categories_collapsed: vec![],
            restore_closed: vec!["ctrl+shift+t".into()],
            screenshot_to_clipboard: vec!["ctrl+alt+s".into()],
            quit: vec!["ctrl+q".into()],
            quit_immediate: Vec::new(),
            quit_minimize: Vec::new(),
            open_markdown: Vec::new(),
            open_explorer: Vec::new(),
            convert_surface: vec!["alt+'".into()],
            convert_to_markdown: Vec::new(),
            convert_to_explorer: Vec::new(),
            new_window: vec!["ctrl+shift+n".into()],
            close_active: vec!["ctrl+w".into()],
            next_tab: Vec::new(),
            prev_tab: Vec::new(),
            find: vec!["ctrl+f".into()],
            copy: vec!["ctrl+shift+c".into()],
            copy_path: vec!["alt+shift+c".into()],
            cut: vec!["ctrl+shift+x".into()],
            select_all: vec!["ctrl+a".into()],
            explorer_refresh: vec!["f5".into()],
            explorer_go_up: vec!["alt+up".into()],
            paste: vec!["ctrl+shift+v".into()],
            zoom_in: vec!["ctrl+=".into(), "ctrl++".into()],
            zoom_out: vec!["ctrl+-".into()],
            zoom_reset: vec!["ctrl+0".into()],
            rename_tab: vec!["f2".into()],
            rename_workspace: vec!["f3".into()],
            rename_workspace_subtitle: vec!["f4".into()],
            image_undo: vec!["ctrl+z".into()],
            image_redo: vec!["ctrl+shift+z".into()],
            toggle_command_palette: vec!["ctrl+shift+p".into()],
            apply_workspace_preset: Vec::new(),
            apply_tab_preset: Vec::new(),
            apply_pane_preset: Vec::new(),
            enter_copy_mode: vec!["ctrl+shift+space".into()],
            minimize_window: Vec::new(),
            maximize_window: Vec::new(),
            close_window: Vec::new(),
            script_bindings: Vec::new(),
            // quick-switch raw 키. 4 프리셋 모두 tab/workspace modifier 기본값이
            // ctrl/alt 로 동일하므로 vim 스타일 키(l/h/j/k)를 공통 적용한다.
            tab_switch_slot_keys: super::default_tab_slot_keys(),
            workspace_switch_slot_keys: super::default_workspace_slot_keys(),
            category_switch_slot_keys: super::default_category_slot_keys(),
            tab_switch_next_key: super::default_tab_next_key(),
            tab_switch_prev_key: super::default_tab_prev_key(),
            workspace_switch_next_key: super::default_workspace_next_key(),
            workspace_switch_prev_key: super::default_workspace_prev_key(),
            category_switch_next_key: super::default_category_next_key(),
            category_switch_prev_key: super::default_category_prev_key(),
        }
    }

    /// List available preset names.
    pub fn preset_names() -> &'static [&'static str] {
        &["Tasty", "Mac", "Windows", "Linux"]
    }

    /// 이름으로 프리셋의 원본 인스턴스를 얻는다. 미리보기/적용 공통 소스.
    pub fn preset_by_name(name: &str) -> Option<Self> {
        match name {
            "Tasty" => Some(Self::preset_tasty()),
            "Mac" => Some(Self::preset_mac()),
            "Windows" => Some(Self::preset_windows()),
            "Linux" => Some(Self::preset_linux()),
            _ => None,
        }
    }

    /// Apply a preset by name. Returns true if found.
    pub fn apply_preset(&mut self, name: &str) -> bool {
        match Self::preset_by_name(name) {
            Some(preset) => {
                *self = preset;
                true
            }
            None => false,
        }
    }
}
