//! 모든 popup의 `PopupDef` 목록. 새 popup을 추가하려면 이 파일에 한 항목만 추가.

use std::sync::OnceLock;

use super::popup::{PopupDef, PopupScope};

/// 프로세스 수명 내내 살아있는 정적 popup 정의 목록.
pub fn all_defs() -> &'static [PopupDef] {
    static DEFS: OnceLock<Vec<PopupDef>> = OnceLock::new();
    DEFS.get_or_init(|| {
        vec![
            PopupDef {
                id: "notifications",
                title_key: "notification_panel.window_title",
                title_fn: None,
                default_size: egui::vec2(350.0, 400.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                draw_fn: super::notification_popup::draw_notification_popup,
            },
            PopupDef {
                id: "convert_surface",
                title_key: "convert_popup.title",
                title_fn: None,
                default_size: super::convert_popup::convert_popup_default_size(),
                sizer: Some(super::convert_popup::convert_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                draw_fn: super::convert_popup::draw_convert_popup,
            },
            PopupDef {
                id: "markdown_open",
                title_key: "dialog.markdown.title",
                title_fn: None,
                default_size: egui::vec2(360.0, 200.0),
                sizer: Some(super::file_open_popup::markdown_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                draw_fn: super::file_open_popup::draw_markdown_open_popup,
            },
            PopupDef {
                id: "html_open",
                title_key: "dialog.html.title",
                title_fn: None,
                default_size: egui::vec2(360.0, 200.0),
                sizer: Some(super::file_open_popup::html_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                draw_fn: super::file_open_popup::draw_html_open_popup,
            },
            PopupDef {
                id: "rename",
                title_key: "rename_dialog.tab_heading",
                title_fn: Some(super::dialog::rename_popup_title),
                default_size: super::dialog::rename_popup_default_size(),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                draw_fn: super::dialog::draw_rename_popup,
            },
            PopupDef {
                id: "search_bar",
                title_key: "search.placeholder",
                title_fn: None,
                default_size: egui::vec2(360.0, 28.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: true,
                sticky_focus: true,
                draw_fn: super::search_bar::draw_search_bar,
            },
            PopupDef {
                id: super::info_modal::INFO_MODAL_ID,
                title_key: "button.ok",
                title_fn: Some(super::info_modal::info_modal_title),
                default_size: egui::vec2(440.0, 160.0),
                sizer: Some(super::info_modal::info_modal_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                draw_fn: super::info_modal::draw_info_modal,
            },
            PopupDef {
                id: super::approval_popup::APPROVAL_POPUP_ID,
                title_key: "approval.popup.title",
                title_fn: Some(super::approval_popup::approval_popup_title),
                default_size: egui::vec2(480.0, 240.0),
                sizer: Some(super::approval_popup::approval_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                draw_fn: super::approval_popup::draw_approval_popup,
            },
            PopupDef {
                id: super::file_handler_picker_popup::PICKER_POPUP_ID,
                title_key: "file_handler.picker.title",
                title_fn: Some(super::file_handler_picker_popup::picker_title),
                default_size: egui::vec2(480.0, 320.0),
                sizer: Some(super::file_handler_picker_popup::picker_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                draw_fn: super::file_handler_picker_popup::draw_file_handler_picker,
            },
            PopupDef {
                id: super::update_popup::UPDATE_POPUP_ID,
                title_key: "update.heading",
                title_fn: None,
                default_size: egui::vec2(440.0, 360.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                draw_fn: super::update_popup::draw_update_popup,
            },
            PopupDef {
                id: super::port_scanner_popup::PORT_SCANNER_POPUP_ID,
                title_key: "port_scanner.heading",
                title_fn: None,
                default_size: egui::vec2(360.0, 320.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                draw_fn: super::port_scanner_popup::draw_port_scanner_popup,
            },
            PopupDef {
                id: super::command_palette_popup::COMMAND_PALETTE_POPUP_ID,
                title_key: "command_palette.heading",
                title_fn: None,
                default_size: egui::vec2(520.0, 360.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: true,
                draw_fn: super::command_palette_popup::draw_command_palette_popup,
            },
            PopupDef {
                id: crate::git_viewer::GIT_VIEWER_POPUP_ID,
                title_key: "git_viewer.heading",
                title_fn: None,
                default_size: egui::vec2(720.0, 540.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                draw_fn: crate::git_viewer::draw_git_viewer_popup,
            },
            PopupDef {
                id: "tools_menu",
                title_key: "tools_menu.title",
                title_fn: None,
                default_size: egui::vec2(160.0, 36.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                draw_fn: super::tools_menu::draw_tools_menu,
            },
        ]
    })
}

/// id로 정의 하나를 찾는다.
pub fn find(id: &str) -> Option<&'static PopupDef> {
    all_defs().iter().find(|d| d.id == id)
}
