use serde::{Deserialize, Serialize};

/// 휠 한 칸의 기본 스크롤 거리(논리 px). 호스트와 플러그인이 같은 값을 사용한다.
pub const DEFAULT_WHEEL_LINE_SCROLL: f32 = 50.0;

/// 빌트인 bashrc 의 *전반부* — LANG/LC_ALL, MSYS PATH, `__tasty_osc7` 함수 정의.
/// 모드와 무관하게 합성 rc 의 *맨 앞* 에 prepend 된다. 사용자 rc 가 이후에 source 된다.
pub const BUILTIN_BASHRC_PRE: &str = r#"# === tasty built-in (auto-generated, do not edit) ===
# Generated by Tasty. Do not edit.
# Put your customizations in ~/.tasty/bashrc.user instead.

# UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Inherit Windows PATH
ORIGINAL_PATH="${ORIGINAL_PATH:-${PATH}}"
export PATH="/usr/local/bin:/usr/bin:/bin:${ORIGINAL_PATH}"

# Report cwd changes with OSC 7. MSYS drive paths are converted in bash; other mounts may use cygpath.
__tasty_osc7() {
    [[ "$PWD" == "$__TASTY_LAST_PWD" ]] && return
    __TASTY_LAST_PWD="$PWD"
    local pwd_emit="$PWD"
    if [[ "$pwd_emit" =~ ^/([a-zA-Z])/(.*)$ ]]; then
        pwd_emit="/${BASH_REMATCH[1]^^}:/${BASH_REMATCH[2]}"
    elif [[ "$pwd_emit" =~ ^/([a-zA-Z])$ ]]; then
        pwd_emit="/${BASH_REMATCH[1]^^}:"
    elif command -v cygpath >/dev/null 2>&1; then
        pwd_emit=$(cygpath -w "$PWD" 2>/dev/null || printf '%s' "$PWD")
        pwd_emit=${pwd_emit//\\//}
        [[ "$pwd_emit" == [A-Za-z]:* ]] && pwd_emit="/${pwd_emit}"
    fi
    printf '\033]7;file://%s%s\033\\' "${HOSTNAME:-localhost}" "$pwd_emit"
}

# Report a cwd-based title when the directory changes: ~ for home, / for root, basename otherwise.
__tasty_title() {
    [[ "$PWD" == "$__TASTY_TITLE_LAST_PWD" ]] && return
    __TASTY_TITLE_LAST_PWD="$PWD"
    local name
    if [[ "$PWD" == "$HOME" ]]; then
        name="~"
    elif [[ "$PWD" == "/" ]]; then
        name="/"
    else
        name="${PWD##*/}"
    fi
    printf '\033]0;%s\007' "$name"
}

# Capture the last command status before running anything else. Report D, then prompt A.
# This function must remain first in PROMPT_COMMAND.
__tasty_osc133_precmd() {
    local ec=$?
    printf '\033]133;D;%s\033\\' "$ec"
    printf '\033]133;A\033\\'
}

# Bash 4.4+ PS0 emits C before command execution; older bash has no fallback here.
# Command text is omitted because the host currently ignores the C-phase payload.
__tasty_osc133_preexec() {
    printf '\033]133;C\033\\'
}
"#;

/// 사용자 rc 뒤에 prompt hook을 설치한다. PROMPT_COMMAND 앞에 Tasty 함수를 추가하고
/// PS0는 C 마커 함수로 덮어쓴다.
pub const BUILTIN_BASHRC_PROMPT: &str = r#"PROMPT_COMMAND="__tasty_osc133_precmd;__tasty_osc7;__tasty_title${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
PS0='$(__tasty_osc133_preexec)'

# === end tasty built-in ===
"#;

/// 생성 bashrc의 동작 버전. 파일의 스탬프가 다르거나 없으면 다시 만든다.
/// 내장 스크립트의 실행 동작을 바꿀 때 증가시킨다. 설명 주석만 바꿀 때는 기존 파일을 재생성하지 않는다.
pub const BUILTIN_BASHRC_STAMP: &str = "# tasty-bashrc-v3";

/// `~/.tasty/bashrc.user`의 초기 시드. 사용자가 자유롭게 수정/리셋할 수 있는 기본값.
pub const INITIAL_USER_BASHRC: &str = r#"# Tasty user bashrc — edit freely.
# Tasty prepends a built-in block (OSC 7 emission etc.) automatically; no need
# to include those here.

# Prompt
PS1='\[\033[32m\]\u@\h\[\033[0m\] \[\033[33m\]\w\[\033[0m\]\n\$ '

# Common aliases
alias ls='ls --color=auto'
alias ll='ls -la'
alias grep='grep --color=auto'
"#;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct GeneralSettings {
    pub shell: String,
    /// Windows 사용자 rc 선택 모드(default/tasty). 빌트인 OSC hook은 두 모드 모두 사용한다.
    #[cfg(windows)]
    pub shell_mode: String,
    pub startup_command: String,
    pub language: String,
    /// Number of scrollback lines to keep.
    pub scrollback_lines: usize,
    /// Show confirmation dialog when closing a surface with a running process.
    pub confirm_close_running: bool,
    /// Enable click-to-move-cursor: clicking on the editable region moves the
    /// shell cursor to that position.
    pub click_to_move_cursor: bool,
    /// When creating a new pane/surface/workspace, inherit the working directory
    /// from the source surface.
    pub inherit_cwd: bool,
    /// Behavior when closing the last window: "ask", "minimize", "quit".
    pub close_behavior: String,
    /// Save and restore layout (workspaces, panes, tabs) on restart.
    pub restore_layout: bool,
    /// 레이아웃 복원 시 터미널 스크롤백도 복원한다. restore_layout이 필요하다.
    /// 옛 restore_terminal_content 키도 읽는다.
    #[serde(alias = "restore_terminal_content")]
    pub restore_surface_content: bool,
    /// 휠 한 칸의 논리 스크롤 거리. 호스트 ScrollArea와 플러그인 경로가 같은 egui 옵션을 사용한다.
    pub wheel_line_scroll: f32,
    /// 터미널 내 링크 클릭 시 요구되는 수식키. "ctrl" | "alt" | "none".
    /// "none"이면 평범한 클릭으로 링크가 열리므로 텍스트 선택과 구분되지 않는 점에 유의.
    pub link_click_modifier: String,
    /// Allow programs in the terminal to read the system clipboard via OSC 52
    /// (`OSC 52 ; c ; ? ST`). Off by default: clipboard read lets any program —
    /// including untrusted remote/SSH processes — silently exfiltrate clipboard
    /// contents (passwords, tokens). When off, read queries get no reply.
    pub allow_clipboard_read: bool,
    /// DECSCNM 화면 반전 표시 여부. 끄면 모드 상태와 질의 응답은 유지하고 렌더링의 색 반전만 생략한다.
    pub reverse_screen_enabled: bool,
    /// BEL 수신 때 알림을 표시한다. 전역 알림·소리 설정도 적용한다.
    /// 꺼도 사용자가 등록한 bell hook은 계속 실행한다.
    pub bell_notification: bool,
    /// 마우스 추적 앱의 첫 클릭 때 Shift 우회 방법을 안내한다. 세션당 한 번이며 끄면 표시하지 않는다.
    /// 옛 right_click_capture_hint 키도 읽는다.
    #[serde(alias = "right_click_capture_hint")]
    pub mouse_capture_hint: bool,
    /// 마우스 캡처 비활성화 블랙리스트 — foreground 프로세스 이름 패턴 목록.
    /// 여기에 매칭되는 TUI 가 surface 의 foreground 일 때, 그 surface 에서는 클릭/
    /// 드래그/버튼 캡처를 끄고(좌클릭=선택, 우클릭=tasty 메뉴 등 로컬 처리) 앱에
    /// 버튼 보고를 보내지 않는다. **휠은 예외로 계속 앱에 보고된다.** 패턴은 `.exe`
    /// 제거·소문자화 후 substring 매칭(또는 `*` 와일드카드)이며, 빈 목록(기본값)이면
    /// 어떤 surface 도 비활성화하지 않는다.
    pub mouse_capture_blacklist: Vec<String>,
    /// foreground 이름에 따라 마우스 캡처 안내 배너만 숨긴다. 캡처 자체는 유지한다.
    /// mouse_capture_blacklist와 같은 매칭 규칙을 사용한다.
    pub mouse_capture_banner_blacklist: Vec<String>,
    /// 워크스페이스 카테고리(사이드바 폴더) 계층을 활성화한다. off(기본)면 사이드바·
    /// 단축키·영속이 현행 평면 동작과 동일하다. on 으로 켜면 normal 외 사용자
    /// 카테고리를 만들 수 있고, off 로 끄면 모든 워크스페이스를 normal 로 귀속한다.
    pub workspace_categories_enabled: bool,
    /// 다음·이전 workspace가 카테고리 경계를 넘어 이동하도록 한다. 끄면 같은 카테고리 안에서 순환한다.
    /// 켜면 인접 카테고리의 처음·마지막 workspace로 이동하며 카테고리 목록 끝에서도 순환한다.
    pub workspace_switch_crosses_category: bool,
    /// Explorer 의 마지막으로 선택한 view mode ("grid" | "list" | "detail"). 사용자가
    /// 툴바 segmented 로 형태를 바꾸면 여기에 기록되고, 새로 생성되는 explorer
    /// surface·내부 탭의 기본 표시 형태로 쓰인다. 알 수 없는 값은
    /// `ExplorerViewMode::from_str` 이 detail 로 fallback (normalize 도 detail 로 교정).
    pub explorer_view_mode: String,
    /// macOS Option+문자를 특수문자 대신 ESC와 기본 문자로 보내 Meta 키로 사용한다. 기본값은 꺼짐이다.
    #[cfg(target_os = "macos")]
    pub option_as_meta: bool,
    /// macOS 단축키의 alt 표시 스타일(alt/cmd/symbol). 저장 토큰은 그대로이고 화면 표시만 바꾼다.
    /// 다른 OS에서는 Alt 표시를 사용한다.
    pub alt_display_style: String,
    /// 단축키 표시 시 `option` 토큰의 텍스트: "option" | "symbol"(⌥). `alt_display_style`
    /// 참고 — 저장↔표시 분리, macOS 전용 UI, 크로스플랫폼 필드. 기본값 "option".
    pub option_display_style: String,
    /// 단축키 표시 시 `shift` 토큰의 텍스트: "shift" | "symbol"(⇧). `alt_display_style`
    /// 참고 — 저장↔표시 분리, macOS 전용 UI, 크로스플랫폼 필드. 기본값 "shift".
    pub shift_display_style: String,
}

/// 파싱된 링크 클릭 수식키.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LinkModifier {
    Ctrl,
    Alt,
    None,
}

impl LinkModifier {
    pub fn parse(s: &str) -> Self {
        match s.to_ascii_lowercase().as_str() {
            "ctrl" | "control" => Self::Ctrl,
            "alt" | "option" => Self::Alt,
            "none" | "off" | "" => Self::None,
            _ => Self::Ctrl,
        }
    }

    /// 현재 modifier 상태가 링크 클릭 트리거 조건을 만족하는지.
    /// 호출자가 winit/macos 등 GUI 레이어에서 추출한 boolean을 그대로 넘긴다.
    pub fn matches(&self, ctrl: bool, alt: bool, super_key: bool) -> bool {
        match self {
            Self::Ctrl => ctrl && !alt && !super_key,
            Self::Alt => alt && !ctrl && !super_key,
            Self::None => true,
        }
    }
}

impl Default for GeneralSettings {
    fn default() -> Self {
        let shell = Self::detect_shell();
        Self {
            shell,
            #[cfg(windows)]
            shell_mode: "default".to_string(),
            startup_command: String::new(),
            language: "en".to_string(),
            scrollback_lines: 10000,
            confirm_close_running: true,
            click_to_move_cursor: true,
            inherit_cwd: true,
            close_behavior: "ask".to_string(),
            restore_layout: true,
            restore_surface_content: true,
            wheel_line_scroll: DEFAULT_WHEEL_LINE_SCROLL,
            link_click_modifier: "ctrl".to_string(),
            allow_clipboard_read: false,
            reverse_screen_enabled: true,
            bell_notification: true,
            mouse_capture_hint: true,
            mouse_capture_blacklist: Vec::new(),
            mouse_capture_banner_blacklist: Vec::new(),
            workspace_categories_enabled: false,
            workspace_switch_crosses_category: false,
            explorer_view_mode: "detail".to_string(),
            #[cfg(target_os = "macos")]
            option_as_meta: false,
            alt_display_style: "alt".to_string(),
            option_display_style: "option".to_string(),
            shift_display_style: "shift".to_string(),
        }
    }
}

/// `*` 와일드카드만 지원하는 소형 glob 매칭 (정규식/`?` 미지원). 패턴·대상 모두
/// 호출 전 소문자/`.exe` 정규화돼 있다고 가정한다. `*` 는 0개 이상의 임의 문자에
/// 대응하며, 앞/뒤/중간 어디에 와도 된다.
fn glob_match(pattern: &str, text: &str) -> bool {
    // 패턴을 `*` 로 분할한 리터럴 조각들을 순서대로 text 에서 소비한다.
    let parts: Vec<&str> = pattern.split('*').collect();
    let starts_wild = pattern.starts_with('*');
    let ends_wild = pattern.ends_with('*');

    let mut cursor = 0usize;
    for (i, part) in parts.iter().enumerate() {
        if part.is_empty() {
            continue;
        }
        let is_first = i == 0;
        let is_last = i == parts.len() - 1;
        if is_first && !starts_wild {
            // 첫 리터럴은 text 시작에 고정.
            if !text[cursor..].starts_with(part) {
                return false;
            }
            cursor += part.len();
        } else if is_last && !ends_wild {
            // 마지막 리터럴은 text 끝에 고정.
            if !text[cursor..].ends_with(part) {
                return false;
            }
            cursor = text.len();
        } else {
            // 중간 리터럴: 다음 출현 위치를 찾아 소비.
            match text[cursor..].find(part) {
                Some(off) => cursor += off + part.len(),
                None => return false,
            }
        }
    }
    true
}

/// `list` 에 `fg_name` 이 매칭되는지 판정하는 공용 헬퍼 — 마우스 캡처 블랙리스트와
/// 배너 억제 블랙리스트가 동일한 매칭 규칙(소문자화·`.exe` 제거 후 substring 또는
/// `*` glob)을 공유하므로 여기서 한 번만 구현한다. 빈 리스트면 항상 false.
fn matches_blacklist(list: &[String], fg_name: &str) -> bool {
    if list.is_empty() {
        return false;
    }
    let lower = fg_name.to_ascii_lowercase();
    let stem = lower.strip_suffix(".exe").unwrap_or(&lower);
    list.iter().any(|pat| {
        let pat = pat.trim().to_ascii_lowercase();
        if pat.is_empty() {
            return false;
        }
        if pat.contains('*') {
            glob_match(&pat, stem)
        } else {
            stem.contains(&pat)
        }
    })
}

impl GeneralSettings {
    /// foreground 이름이 캡처 제외 목록과 맞는지 확인한다. 버튼 캡처는 끄지만 휠은 계속 보고한다.
    pub fn mouse_capture_disabled_for(&self, fg_name: &str) -> bool {
        matches_blacklist(&self.mouse_capture_blacklist, fg_name)
    }

    /// foreground 이름이 안내 배너 제외 목록과 맞는지 확인한다. 캡처 자체의 설정과는 별개다.
    pub fn mouse_capture_banner_disabled_for(&self, fg_name: &str) -> bool {
        matches_blacklist(&self.mouse_capture_banner_blacklist, fg_name)
    }

    /// 사용할 셸 경로를 찾고 없으면 빈 문자열을 반환한다.
    pub fn detect_shell() -> String {
        Self::detect_bash().unwrap_or_default()
    }

    /// Windows는 Git Bash 후보, 다른 OS는 로그인 셸·SHELL·일반 셸 경로 순으로 찾는다.
    pub fn detect_bash() -> Option<String> {
        #[cfg(windows)]
        {
            let candidates = [
                std::env::var("ProgramFiles")
                    .map(|p| format!("{}/Git/bin/bash.exe", p))
                    .unwrap_or_default(),
                "C:/Program Files/Git/bin/bash.exe".to_string(),
                "C:/Program Files (x86)/Git/bin/bash.exe".to_string(),
            ];
            for path in &candidates {
                if !path.is_empty() && std::path::Path::new(path).exists() {
                    return Some(path.clone());
                }
            }
            None
        }
        #[cfg(not(windows))]
        {
            // 1. Check /etc/passwd for the user's login shell (most authoritative after chsh)
            if let Some(login_shell) = Self::login_shell_from_passwd()
                && std::path::Path::new(&login_shell).exists()
            {
                return Some(login_shell);
            }
            // 2. Fall back to $SHELL env var
            if let Ok(shell) = std::env::var("SHELL")
                && std::path::Path::new(&shell).exists()
            {
                return Some(shell);
            }
            // 3. Common paths
            for path in &["/bin/zsh", "/bin/bash", "/bin/sh"] {
                if std::path::Path::new(path).exists() {
                    return Some(path.to_string());
                }
            }
            None
        }
    }

    /// Read the user's login shell from /etc/passwd.
    #[cfg(not(windows))]
    fn login_shell_from_passwd() -> Option<String> {
        use std::io::BufRead;
        // SAFETY: getuid는 POSIX thread-safe 시스템콜, errno도 안 set한다.
        let uid = unsafe { libc::getuid() };
        let file = std::fs::File::open("/etc/passwd").ok()?;
        for line in std::io::BufReader::new(file).lines() {
            let line = line.ok()?;
            let fields: Vec<&str> = line.split(':').collect();
            if fields.len() >= 7
                && let Ok(entry_uid) = fields[2].parse::<u32>()
                && entry_uid == uid
            {
                return Some(fields[6].to_string());
            }
        }
        None
    }

    /// 경로가 존재하는지 확인한다. Windows에서는 파일명에 bash 또는 zsh가 포함돼야 한다.
    /// 실행 가능 여부나 실제 셸 호환성까지 검사하지는 않는다.
    pub fn is_shell_valid(&self) -> bool {
        if self.shell.is_empty() {
            return false;
        }
        let path = std::path::Path::new(&self.shell);
        if !path.exists() {
            return false;
        }
        #[cfg(windows)]
        {
            let filename = path
                .file_name()
                .and_then(|f| f.to_str())
                .unwrap_or("")
                .to_ascii_lowercase();
            filename.contains("bash") || filename.contains("zsh")
        }
        #[cfg(not(windows))]
        {
            true
        }
    }

    /// bash 통합의 --rcfile 인자. zsh는 환경변수로 설정하며 다른 셸에는 주입하지 않는다.
    pub fn effective_shell_args(&self) -> Vec<String> {
        self.effective_shell_args_in(tasty_dir().as_deref())
    }

    /// 시험에서 전역 환경변수 대신 명시한 홈 경로를 사용한다.
    fn effective_shell_args_in(&self, dir: Option<&std::path::Path>) -> Vec<String> {
        match tasty_utils::shell_family::ShellFamily::detect(&self.shell) {
            tasty_utils::shell_family::ShellFamily::Bash => {
                ensure_compiled_bashrc_in(dir);
                bash_rcfile_args_in(self, dir)
            }
            _ => Vec::new(),
        }
    }

    /// zsh 통합에 필요한 ZDOTDIR 환경변수. bash 통합은 인자를 사용한다.
    pub fn effective_shell_envs(&self) -> Vec<(String, String)> {
        self.effective_shell_envs_in(tasty_dir().as_deref())
    }

    /// 시험에서 명시한 홈 경로로 환경변수 목록을 만든다.
    fn effective_shell_envs_in(&self, dir: Option<&std::path::Path>) -> Vec<(String, String)> {
        if tasty_utils::shell_family::ShellFamily::detect(&self.shell)
            != tasty_utils::shell_family::ShellFamily::Zsh
        {
            return Vec::new();
        }
        zsh_shell_envs_in(dir)
    }
}

/// zsh 통합의 환경변수. 홈을 찾지 못하면 wrapper를 만들거나 ZDOTDIR를 주입하지 않는다.
fn zsh_shell_envs_in(dir: Option<&std::path::Path>) -> Vec<(String, String)> {
    // 상대 ZDOTDIR가 자식 셸의 cwd에서 다시 해석되지 않도록 홈이 없으면 생략한다.
    let Some(zdotdir) = tasty_zsh_integration_dir_in(dir) else {
        return Vec::new();
    };
    ensure_compiled_zshenv_in(dir);
    let mut envs = vec![("ZDOTDIR".to_string(), zdotdir.to_string_lossy().to_string())];
    // 원래 ZDOTDIR의 미설정과 빈 값을 구분해 wrapper가 복원할 수 있도록 전달한다.
    if let Ok(orig) = std::env::var("ZDOTDIR") {
        envs.push(("__TASTY_ORIG_ZDOTDIR_SET".to_string(), "1".to_string()));
        envs.push(("__TASTY_ORIG_ZDOTDIR".to_string(), orig));
    }
    envs
}

/// Windows bash는 --rcfile만, 다른 OS는 --rcfile과 -i를 사용한다.
/// bash 로그인 모드는 --rcfile을 무시하므로 호스트의 -li 자동 추가와 함께 사용하면 안 된다.
/// 스크립트 합성은 공유하고 Windows의 사용자 rc 선택만 shell_mode를 따른다.
#[cfg(windows)]
fn bash_rcfile_args_in(settings: &GeneralSettings, dir: Option<&std::path::Path>) -> Vec<String> {
    // 모드는 사용자 rc 선택만 바꾼다. 홈이 없으면 상대 rc 경로를 내보내지 않는다.
    let rcfile = match settings.shell_mode.as_str() {
        "tasty" => tasty_bashrc_path_in(dir),
        _ => tasty_bashrc_default_path_in(dir),
    };
    let Some(rcfile) = rcfile else {
        return Vec::new();
    };
    vec!["--rcfile".to_string(), rcfile.replace('\\', "/")]
}

/// 비 Windows bash는 사용자 로그인 프로필을 읽는 default rc만 사용한다.
#[cfg(not(windows))]
fn bash_rcfile_args_in(_settings: &GeneralSettings, dir: Option<&std::path::Path>) -> Vec<String> {
    // 홈이 없으면 --rcfile과 그에 필요한 -i를 함께 생략한다.
    let Some(rcfile) = tasty_bashrc_default_path_in(dir) else {
        return Vec::new();
    };
    vec!["--rcfile".to_string(), rcfile, "-i".to_string()]
}

/// Path to Tasty's compiled bashrc for **tasty 모드** (BUILTIN_PRE + ~/.tasty/bashrc.user + BUILTIN_PROMPT).
/// Windows 전용 개념(`shell_mode` UI 토글) — 비-Windows 는 이 파일을 만들지 않는다.
pub fn tasty_bashrc_path() -> Option<String> {
    tasty_bashrc_path_in(tasty_dir().as_deref())
}

fn tasty_bashrc_path_in(dir: Option<&std::path::Path>) -> Option<String> {
    Some(dir?.join("bashrc").to_string_lossy().to_string())
}

/// Path to Tasty's compiled bashrc for **default 모드**
/// (BUILTIN_PRE + [`default_mode_user_source`] + BUILTIN_PROMPT). 비-Windows 는
/// 유일하게 쓰는 합성 rc 파일이다(셸 모드 토글이 없어 이거 하나뿐).
pub fn tasty_bashrc_default_path() -> Option<String> {
    tasty_bashrc_default_path_in(tasty_dir().as_deref())
}

fn tasty_bashrc_default_path_in(dir: Option<&std::path::Path>) -> Option<String> {
    Some(dir?.join("bashrc.default").to_string_lossy().to_string())
}

/// Path to the user-editable bashrc fragment. Windows 전용(tasty 모드에서만 쓰임).
pub fn tasty_bashrc_user_path() -> Option<String> {
    tasty_bashrc_user_path_in(tasty_dir().as_deref())
}

fn tasty_bashrc_user_path_in(dir: Option<&std::path::Path>) -> Option<String> {
    Some(dir?.join("bashrc.user").to_string_lossy().to_string())
}

/// zsh가 처음 읽을 .zshenv wrapper 디렉터리.
pub fn tasty_zsh_integration_dir() -> Option<std::path::PathBuf> {
    tasty_zsh_integration_dir_in(tasty_dir().as_deref())
}

fn tasty_zsh_integration_dir_in(dir: Option<&std::path::Path>) -> Option<std::path::PathBuf> {
    Some(dir?.join("zsh-integration"))
}

/// Windows는 ~/.bashrc를 읽는다. 다른 OS는 .bash_profile, .bash_login, .profile 중
/// 처음 존재하는 파일을 읽어 로그인 프로필 순서를 재현한다. 그 프로필이 .bashrc를 읽지 않으면
/// 여기서도 따로 읽지 않는다.
#[cfg(windows)]
fn default_mode_user_source() -> &'static str {
    "[ -f ~/.bashrc ] && source ~/.bashrc\n"
}
#[cfg(not(windows))]
fn default_mode_user_source() -> &'static str {
    "if [ -f ~/.bash_profile ]; then\n    source ~/.bash_profile\nelif [ -f ~/.bash_login ]; then\n    source ~/.bash_login\nelif [ -f ~/.profile ]; then\n    source ~/.profile\nfi\n"
}

/// default 모드용 합성 rc 본문. BUILTIN PRE → [`default_mode_user_source`] → BUILTIN
/// PROMPT. 사용자 rc 가 PROMPT_COMMAND/PS0 를 덮어써도 마지막에 빌트인 훅이 이긴다.
pub fn compose_default_mode_bashrc() -> String {
    format!(
        "{}\n{}\n{}{}",
        BUILTIN_BASHRC_STAMP,
        BUILTIN_BASHRC_PRE,
        default_mode_user_source(),
        BUILTIN_BASHRC_PROMPT,
    )
}

/// tasty 모드용 합성 rc 본문. BUILTIN PRE → tasty user rc → BUILTIN PROMPT.
/// 사용자 영역 (`~/.tasty/bashrc.user`) 이 PROMPT_COMMAND 를 덮어써도 마지막에 prepend.
/// Windows 전용(`shell_mode` UI 토글이 있어야 의미가 있다).
pub fn compose_tasty_mode_bashrc(user_content: &str) -> String {
    format!(
        "{}\n{}\n{}\n{}",
        BUILTIN_BASHRC_STAMP, BUILTIN_BASHRC_PRE, user_content, BUILTIN_BASHRC_PROMPT,
    )
}

/// tasty_home의 TASTY_HOME·debug/release 규칙을 따라 통합 파일 루트를 구한다.
/// 상대 경로는 절대화하며 실패 경고는 프로세스당 한 번만 남긴다.
fn tasty_dir() -> Option<std::path::PathBuf> {
    let home = tasty_utils::path::tasty_home();
    if home.is_none() {
        static WARNED: std::sync::Once = std::sync::Once::new();
        WARNED.call_once(|| {
            tracing::warn!(
                "tasty home directory unresolved (TASTY_HOME empty and base dirs unavailable) \
                 — shell integration is disabled: bashrc / zsh-integration paths cannot be derived"
            );
        });
        return None;
    }
    let cwd = std::env::current_dir();
    if let Err(e) = &cwd
        && home.as_ref().is_some_and(|h| !h.is_absolute())
    {
        static WARNED: std::sync::Once = std::sync::Once::new();
        WARNED.call_once(|| {
            tracing::warn!(
                "tasty home is a relative path but the current directory is unreadable ({e}) \
                 — shell integration is disabled: relative bashrc / ZDOTDIR paths would be \
                 re-resolved against the child shell's own directory"
            );
        });
    }
    resolve_tasty_dir(home, cwd.ok())
}

/// 홈 후보를 확정한다. None이면 그대로 반환하고 상대 경로는 주어진 cwd 기준으로 절대화한다.
/// cwd도 없으면 None이다. 빈 경로로 대체해 호스트나 자식 셸의 실행 위치에 파일을 만들지 않는다.
fn resolve_tasty_dir(
    home: Option<std::path::PathBuf>,
    cwd: Option<std::path::PathBuf>,
) -> Option<std::path::PathBuf> {
    let dir = home?;
    if dir.is_absolute() {
        return Some(dir);
    }
    Some(cwd?.join(dir))
}

/// 사용자 편집 파일을 로드. 파일이 없으면 `INITIAL_USER_BASHRC`를 반환(파일은 생성하지 않음).
pub fn load_user_bashrc() -> String {
    load_user_bashrc_in(tasty_dir().as_deref())
}

/// [`load_user_bashrc`] 의 본문 — 루트를 인자로 받는다(위 `_in` 들과 같은 이유).
fn load_user_bashrc_in(dir: Option<&std::path::Path>) -> String {
    // 홈이 없으면 현재 디렉터리의 bashrc.user를 대신 읽지 않는다.
    let Some(path) = tasty_bashrc_user_path_in(dir) else {
        return INITIAL_USER_BASHRC.to_string();
    };
    match std::fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => INITIAL_USER_BASHRC.to_string(),
    }
}

/// 사용자 파일을 쓰고 합성 bashrc를 다시 만든다. 어느 단계든 실패하면 호출자에게 알린다.
/// 사용자 파일 저장 후 합성 실패라면 사용자 본문은 남지만 셸에 아직 적용되지 않은 상태다.
pub fn save_user_bashrc(user_content: &str) -> Result<(), String> {
    save_user_bashrc_in(tasty_dir().as_deref(), user_content)
}

/// [`save_user_bashrc`] 의 본문 — 루트를 인자로 받는다(위 `_in` 들과 같은 이유).
fn save_user_bashrc_in(dir: Option<&std::path::Path>, user_content: &str) -> Result<(), String> {
    // 홈이 없으면 현재 디렉터리에 대신 저장하지 않는다.
    let (Some(user_path), Some(compiled_path)) =
        (tasty_bashrc_user_path_in(dir), tasty_bashrc_path_in(dir))
    else {
        return Err("tasty home directory unresolved — the edit was not persisted".to_string());
    };
    if !ensure_bashrc_parent_dir(&user_path) {
        return Err(format!("parent directory unavailable ({user_path})"));
    }
    std::fs::write(&user_path, user_content).map_err(|e| format!("write {user_path}: {e}"))?;
    let compiled = compose_tasty_mode_bashrc(user_content);
    if !write_generated_file(std::path::Path::new(&compiled_path), &compiled) {
        return Err(format!(
            "compiled rc {compiled_path} not written — the saved edit is not in effect"
        ));
    }
    Ok(())
}

/// `user_path` 의 부모 디렉토리를 보장한다. 생성 실패 시 `false`(호출자는 이후 쓰기
/// 단계를 건너뛴다). 부모가 없는 경로(루트 등)는 이미 존재하는 것으로 간주.
fn ensure_bashrc_parent_dir(user_path: &str) -> bool {
    let Some(parent) = std::path::Path::new(user_path).parent() else {
        return true;
    };
    if let Err(e) = std::fs::create_dir_all(parent) {
        tracing::warn!("create_dir_all for bashrc failed: {e}");
        return false;
    }
    true
}

/// 같은 디렉터리의 임시 파일에 쓴 뒤 rename으로 교체한다. 부모 디렉터리는 호출자가 준비한다.
/// Unix 파일 권한은 0644다. 성공 여부를 반환하며 경고는 실패 지점에서 남긴다.
fn write_generated_file(path: &std::path::Path, content: &str) -> bool {
    let Some(file_name) = path.file_name().and_then(|f| f.to_str()) else {
        tracing::warn!("write_generated_file: path has no file name: {path:?}");
        return false;
    };
    let tmp_path = path.with_file_name(format!("{file_name}.tmp"));
    if !write_tmp_file(&tmp_path, content) {
        return false;
    }
    if let Err(e) = std::fs::rename(&tmp_path, path) {
        tracing::warn!("rename {tmp_path:?} -> {path:?} failed: {e}");
        return false;
    }
    true
}

/// 임시 파일에 내용과 Unix 권한을 설정한다.
fn write_tmp_file(tmp_path: &std::path::Path, content: &str) -> bool {
    if let Err(e) = std::fs::write(tmp_path, content) {
        tracing::warn!("write {tmp_path:?} failed: {e}");
        return false;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Err(e) = std::fs::set_permissions(tmp_path, std::fs::Permissions::from_mode(0o644)) {
            tracing::warn!("set_permissions for {tmp_path:?} failed: {e}");
        }
    }
    true
}

/// 합성 rc/wrapper 파일이 주어진 버전 스탬프를 담고 있는지. 파일이 없거나 스탬프가
/// 다르면 (구버전/무표기) false — 재생성 대상. bash/zsh 양쪽이 공유하는 스탬프
/// 판정 로직(스탬프 문자열만 다르다).
fn generated_file_stamp_current(path: &str, stamp: &str) -> bool {
    std::fs::read_to_string(path).is_ok_and(|s| s.lines().any(|l| l.trim() == stamp))
}

/// 없는 파일이나 이전 동작 스탬프의 bashrc를 다시 만든다.
/// 사용자 bashrc.user는 유지하며 tasty 모드는 Windows에서만 생성한다. 홈 경로는 호출자가 전달한다.
fn ensure_compiled_bashrc_in(dir: Option<&std::path::Path>) {
    // tasty 모드 합성 rc — Windows 전용(shell_mode UI 토글이 있어야 의미 있음).
    #[cfg(windows)]
    if let Some(tasty_path) = tasty_bashrc_path_in(dir)
        && !generated_file_stamp_current(&tasty_path, BUILTIN_BASHRC_STAMP)
    {
        let user = load_user_bashrc_in(dir);
        // 부팅 중 재생성 실패는 경고하고 다음 부팅에서 다시 시도한다.
        if let Err(reason) = save_user_bashrc_in(dir, &user) {
            tracing::warn!("regenerate tasty-mode bashrc failed: {reason}");
        }
    }
    // 기본 rc는 양쪽 OS에서 사용한다. 홈이 없으면 생성과 --rcfile 주입을 모두 생략한다.
    let Some(default_path) = tasty_bashrc_default_path_in(dir) else {
        return;
    };
    if !generated_file_stamp_current(&default_path, BUILTIN_BASHRC_STAMP) {
        let compiled = compose_default_mode_bashrc();
        if !ensure_bashrc_parent_dir(&default_path) {
            return;
        }
        write_generated_file(std::path::Path::new(&default_path), &compiled);
    }
}

/// zsh wrapper. hook을 등록하고 ZDOTDIR를 복원한 뒤 원래 .zshenv를 읽는다.
pub const BUILTIN_ZSHENV_BODY: &str = r#"# Generated by Tasty. Do not edit.

# Install zsh precmd/preexec hooks for OSC 133.
autoload -Uz add-zsh-hook

__tasty_osc133_precmd() {
    local ec=$?
    printf '\033]133;D;%s\033\\' "$ec"
    printf '\033]133;A\033\\'
}
__tasty_osc133_preexec() {
    printf '\033]133;C;cmd=%s\033\\' "$1"
}
add-zsh-hook precmd __tasty_osc133_precmd
add-zsh-hook preexec __tasty_osc133_preexec

# User startup files can replace these functions or hook arrays. This wrapper does not restore them afterward.

# Restore the original ZDOTDIR before sourcing the user .zshenv.
if [ -n "${__TASTY_ORIG_ZDOTDIR_SET:-}" ]; then
    export ZDOTDIR="$__TASTY_ORIG_ZDOTDIR"
else
    unset ZDOTDIR
fi
unset __TASTY_ORIG_ZDOTDIR_SET __TASTY_ORIG_ZDOTDIR

__tasty_real_zdotdir="${ZDOTDIR:-$HOME}"
[ -f "$__tasty_real_zdotdir/.zshenv" ] && source "$__tasty_real_zdotdir/.zshenv"
unset __tasty_real_zdotdir
"#;

/// 생성 zshenv의 동작 버전. 실행 동작을 바꿀 때 증가시킨다. 설명 주석 변경은 기존 파일 재생성을 요구하지 않는다.
pub const BUILTIN_ZSHENV_STAMP: &str = "# tasty-zshenv-v1";

/// Path to Tasty's compiled zsh wrapper `.zshenv` (`~/.tasty/zsh-integration/.zshenv`).
pub fn tasty_zshenv_path() -> Option<std::path::PathBuf> {
    tasty_zshenv_path_in(tasty_dir().as_deref())
}

fn tasty_zshenv_path_in(dir: Option<&std::path::Path>) -> Option<std::path::PathBuf> {
    Some(tasty_zsh_integration_dir_in(dir)?.join(".zshenv"))
}

/// 합성 `.zshenv` 본문. 스탬프 + [`BUILTIN_ZSHENV_BODY`].
pub fn compose_zsh_zshenv() -> String {
    format!("{}\n{}", BUILTIN_ZSHENV_STAMP, BUILTIN_ZSHENV_BODY)
}

/// wrapper가 없거나 동작 스탬프가 다르면 다시 만든다. 원래 사용자 .zshenv는 덮어쓰지 않는다.
fn ensure_compiled_zshenv_in(dir: Option<&std::path::Path>) {
    // 홈 미해석이면 CWD 에 `zsh-integration/` 을 만들지 않는다(`tasty_dir` 참고).
    let (Some(zdir), Some(path)) = (tasty_zsh_integration_dir_in(dir), tasty_zshenv_path_in(dir))
    else {
        return;
    };
    if let Err(e) = std::fs::create_dir_all(&zdir) {
        tracing::warn!("create_dir_all for zsh-integration failed: {e}");
        return;
    }
    let path_str = path.to_string_lossy().to_string();
    if generated_file_stamp_current(&path_str, BUILTIN_ZSHENV_STAMP) {
        return;
    }
    let compiled = compose_zsh_zshenv();
    write_generated_file(&path, &compiled);
}

/// 시험은 홈=None 입력과 상대 홈의 절대화·각 호출자의 전달을 확인한다.
/// 실제 OS 홈 조회가 None이 되는 환경은 이 시험에서 재현하지 않는다. HOME을 지워도
/// passwd에서 홈을 찾을 수 있어 순수 함수에 None을 주입하는 검사와 구분한다.
#[cfg(test)]
mod tests {
    use super::*;

    fn settings_with_blacklist(patterns: &[&str]) -> GeneralSettings {
        GeneralSettings {
            mouse_capture_blacklist: patterns.iter().map(|s| s.to_string()).collect(),
            ..GeneralSettings::default()
        }
    }

    #[test]
    fn mouse_capture_substring_hit_and_miss() {
        let g = settings_with_blacklist(&["htop"]);
        assert!(g.mouse_capture_disabled_for("htop"));
        assert!(g.mouse_capture_disabled_for("htop-vim")); // substring
        assert!(!g.mouse_capture_disabled_for("vim"));
    }

    #[test]
    fn mouse_capture_case_insensitive() {
        let g = settings_with_blacklist(&["HTOP"]);
        assert!(g.mouse_capture_disabled_for("htop"));
        assert!(g.mouse_capture_disabled_for("HTOP"));
    }

    #[test]
    fn mouse_capture_strips_exe_suffix() {
        let g = settings_with_blacklist(&["htop"]);
        assert!(g.mouse_capture_disabled_for("htop.exe"));
        assert!(g.mouse_capture_disabled_for("HTOP.EXE"));
    }

    #[test]
    fn mouse_capture_empty_blacklist_never_matches() {
        let g = settings_with_blacklist(&[]);
        assert!(!g.mouse_capture_disabled_for("htop"));
    }

    #[test]
    fn mouse_capture_blank_pattern_ignored() {
        // 공백/빈 줄 패턴이 전체 매칭으로 새지 않아야 한다.
        let g = settings_with_blacklist(&["   ", ""]);
        assert!(!g.mouse_capture_disabled_for("htop"));
        assert!(!g.mouse_capture_disabled_for("anything"));
    }

    #[test]
    fn mouse_capture_glob_wildcard() {
        let g = settings_with_blacklist(&["ht*"]);
        assert!(g.mouse_capture_disabled_for("htop"));
        assert!(!g.mouse_capture_disabled_for("vim"));

        let g = settings_with_blacklist(&["*top"]);
        assert!(g.mouse_capture_disabled_for("htop"));
        assert!(!g.mouse_capture_disabled_for("htopx"));

        let g = settings_with_blacklist(&["h*p"]);
        assert!(g.mouse_capture_disabled_for("htop"));
        assert!(!g.mouse_capture_disabled_for("hat"));
    }

    #[test]
    fn mouse_capture_blacklist_defaults_empty() {
        let g = GeneralSettings::default();
        assert!(g.mouse_capture_blacklist.is_empty());
    }

    #[test]
    fn mouse_capture_banner_disabled_for_matches_pattern() {
        let mut s = GeneralSettings::default();
        s.mouse_capture_banner_blacklist = vec!["vim".to_string()];
        assert!(s.mouse_capture_banner_disabled_for("vim"));
        assert!(!s.mouse_capture_banner_disabled_for("htop"));
    }

    #[test]
    fn mouse_capture_banner_blacklist_independent_of_capture_blacklist() {
        let mut s = GeneralSettings::default();
        s.mouse_capture_blacklist = vec!["htop".to_string()];
        s.mouse_capture_banner_blacklist = vec!["vim".to_string()];
        assert!(s.mouse_capture_disabled_for("htop"));
        assert!(!s.mouse_capture_disabled_for("vim"));
        assert!(s.mouse_capture_banner_disabled_for("vim"));
        assert!(!s.mouse_capture_banner_disabled_for("htop"));
    }

    #[test]
    fn mouse_capture_banner_blacklist_defaults_empty() {
        let g = GeneralSettings::default();
        assert!(g.mouse_capture_banner_blacklist.is_empty());
    }

    #[test]
    fn legacy_restore_terminal_content_key_still_loads() {
        let g: GeneralSettings = toml::from_str("restore_terminal_content = false").unwrap();
        assert!(!g.restore_surface_content);
    }

    #[test]
    fn new_restore_surface_content_key_loads() {
        let g: GeneralSettings = toml::from_str("restore_surface_content = false").unwrap();
        assert!(!g.restore_surface_content);
    }

    #[test]
    fn reverse_screen_enabled_defaults_true() {
        let g = GeneralSettings::default();
        assert!(g.reverse_screen_enabled);
    }

    #[test]
    fn reverse_screen_enabled_missing_key_uses_default() {
        let g: GeneralSettings = toml::from_str("scrollback_lines = 5000").unwrap();
        assert!(g.reverse_screen_enabled);
    }

    #[test]
    fn reverse_screen_enabled_round_trips() {
        let g: GeneralSettings = toml::from_str("reverse_screen_enabled = false").unwrap();
        assert!(!g.reverse_screen_enabled);
        let out = toml::to_string(&g).unwrap();
        let g2: GeneralSettings = toml::from_str(&out).unwrap();
        assert!(!g2.reverse_screen_enabled);
    }

    #[test]
    fn bell_notification_defaults_true() {
        let g = GeneralSettings::default();
        assert!(g.bell_notification);
    }

    #[test]
    fn bell_notification_missing_key_uses_default() {
        let g: GeneralSettings = toml::from_str("scrollback_lines = 5000").unwrap();
        assert!(g.bell_notification);
    }

    #[test]
    fn bell_notification_round_trips() {
        let g: GeneralSettings = toml::from_str("bell_notification = false").unwrap();
        assert!(!g.bell_notification);
        let out = toml::to_string(&g).unwrap();
        let g2: GeneralSettings = toml::from_str(&out).unwrap();
        assert!(!g2.bell_notification);
    }

    #[test]
    fn explorer_view_mode_defaults_to_detail() {
        let g = GeneralSettings::default();
        assert_eq!(g.explorer_view_mode, "detail");
    }

    #[test]
    fn explorer_view_mode_round_trips() {
        let g: GeneralSettings = toml::from_str("explorer_view_mode = \"list\"").unwrap();
        assert_eq!(g.explorer_view_mode, "list");
        let out = toml::to_string(&g).unwrap();
        let g2: GeneralSettings = toml::from_str(&out).unwrap();
        assert_eq!(g2.explorer_view_mode, "list");
    }

    #[test]
    fn explorer_view_mode_missing_key_uses_default() {
        let g: GeneralSettings = toml::from_str("scrollback_lines = 5000").unwrap();
        assert_eq!(g.explorer_view_mode, "detail");
    }

    #[cfg(windows)]
    fn settings_with_mode(mode: &str) -> GeneralSettings {
        GeneralSettings {
            // 실제 Git Bash 설치와 무관하게 셸 종류 판정에 사용할 이름을 지정한다.
            shell: "bash.exe".to_string(),
            shell_mode: mode.to_string(),
            ..GeneralSettings::default()
        }
    }

    fn settings_with_shell(shell: &str) -> GeneralSettings {
        GeneralSettings {
            shell: shell.to_string(),
            ..GeneralSettings::default()
        }
    }

    // 대부분의 시험은 홈을 직접 주입해 환경변수를 바꾸지 않는다.
    // 상대 TASTY_HOME 시험과 CWD 오염 검사는 같은 SERIAL 락으로 직렬화한다.
    static SERIAL: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// 환경변수를 바꾸지 않고 함수에 직접 전달할 임시 홈.
    struct TmpHome {
        dir: tempfile::TempDir,
    }
    impl TmpHome {
        fn new() -> Self {
            Self {
                dir: tempfile::tempdir().expect("tempdir"),
            }
        }
        fn path(&self) -> &std::path::Path {
            self.dir.path()
        }
    }

    #[cfg(windows)]
    #[test]
    fn default_mode_uses_default_rc_file() {
        let home = TmpHome::new();
        let args = settings_with_mode("default").effective_shell_args_in(Some(home.path()));
        assert!(args.iter().any(|a| a == "--rcfile"));
        assert!(args.iter().any(|a| {
            a.ends_with("bashrc.default") && std::path::Path::new(a).starts_with(home.path())
        }));
    }

    #[cfg(windows)]
    #[test]
    fn unknown_mode_falls_back_to_default_rc_file() {
        let home = TmpHome::new();
        let args = settings_with_mode("fast").effective_shell_args_in(Some(home.path()));
        assert!(args.iter().any(|a| a == "--rcfile"));
        assert!(args.iter().any(|a| {
            a.ends_with("bashrc.default") && std::path::Path::new(a).starts_with(home.path())
        }));
    }

    #[cfg(windows)]
    #[test]
    fn tasty_mode_uses_tasty_rc_file() {
        let home = TmpHome::new();
        let args = settings_with_mode("tasty").effective_shell_args_in(Some(home.path()));
        assert_eq!(args.len(), 2);
        assert_eq!(args[0], "--rcfile");
        assert!(args.iter().any(|a| {
            a.ends_with("bashrc") && std::path::Path::new(a).starts_with(home.path())
        }));
        assert!(args.iter().all(|a| !a.ends_with("bashrc.default")));
    }

    #[cfg(windows)]
    #[test]
    fn default_mode_compiled_rc_sources_user_bashrc() {
        let compiled = compose_default_mode_bashrc();
        assert!(compiled.contains("__tasty_osc7")); // BUILTIN PRE 적용
        assert!(compiled.contains("source ~/.bashrc")); // 사용자 rc 호출
        assert!(compiled.contains("PROMPT_COMMAND=")); // BUILTIN PROMPT 적용
    }

    #[cfg(not(windows))]
    #[test]
    fn default_mode_compiled_rc_searches_login_profiles_on_unix() {
        let compiled = compose_default_mode_bashrc();
        assert!(compiled.contains("__tasty_osc7")); // BUILTIN PRE 적용
        assert!(compiled.contains(".bash_profile"));
        assert!(compiled.contains(".bash_login"));
        assert!(compiled.contains(".profile"));
        assert!(compiled.contains("PROMPT_COMMAND=")); // BUILTIN PROMPT 적용
    }

    #[test]
    fn tasty_mode_compiled_rc_wraps_user_content() {
        let compiled = compose_tasty_mode_bashrc("alias hi='echo hi'\n");
        assert!(compiled.contains("__tasty_osc7"));
        assert!(compiled.contains("alias hi='echo hi'"));
        assert!(compiled.contains("PROMPT_COMMAND="));
        // PROMPT_COMMAND 는 사용자 본문 *뒤* 에 와야 한다.
        let user_pos = compiled.find("alias hi").unwrap();
        let prompt_pos = compiled.find("PROMPT_COMMAND=").unwrap();
        assert!(prompt_pos > user_pos);
    }

    #[test]
    fn compiled_rcs_define_and_join_tasty_title() {
        for compiled in [
            compose_default_mode_bashrc(),
            compose_tasty_mode_bashrc("alias hi='echo hi'\n"),
        ] {
            assert!(compiled.contains("__tasty_title()"), "definition missing");
            assert!(
                compiled.contains(
                    r#"PROMPT_COMMAND="__tasty_osc133_precmd;__tasty_osc7;__tasty_title"#
                ),
                "PROMPT_COMMAND joint missing"
            );
        }
    }

    #[test]
    fn compiled_rcs_wire_osc133_hooks() {
        for compiled in [compose_default_mode_bashrc(), compose_tasty_mode_bashrc("")] {
            assert!(
                compiled.contains("__tasty_osc133_precmd()"),
                "precmd definition missing"
            );
            assert!(
                compiled.contains("__tasty_osc133_preexec()"),
                "preexec definition missing"
            );
            assert!(compiled.contains(r#"PS0='$(__tasty_osc133_preexec)'"#));
            assert!(compiled.contains(r#"\033]133;A\033\\"#));
            // 현재 C-phase parser는 cmd payload를 저장하지 않는다.
            assert!(compiled.contains(r#"\033]133;C\033\\"#));
            assert!(compiled.contains(r#"\033]133;D;%s\033\\"#));
        }
    }

    #[test]
    fn compiled_rcs_carry_version_stamp() {
        for compiled in [compose_default_mode_bashrc(), compose_tasty_mode_bashrc("")] {
            assert!(
                compiled.lines().any(|l| l.trim() == BUILTIN_BASHRC_STAMP),
                "version stamp missing"
            );
        }
    }

    #[test]
    fn ensure_compiled_bashrc_regenerates_stale_files() {
        let home = TmpHome::new();
        let default_path =
            tasty_bashrc_default_path_in(Some(home.path())).expect("injected home always resolves");
        std::fs::create_dir_all(std::path::Path::new(&default_path).parent().unwrap()).unwrap();
        std::fs::write(&default_path, "# old builtin without stamp\n").unwrap();
        #[cfg(windows)]
        let tasty_path = {
            let p = tasty_bashrc_path_in(Some(home.path())).expect("injected home always resolves");
            std::fs::write(&p, "# old builtin without stamp\n").unwrap();
            p
        };

        ensure_compiled_bashrc_in(Some(home.path()));

        #[cfg(windows)]
        let paths = [default_path.as_str(), tasty_path.as_str()];
        #[cfg(not(windows))]
        let paths = [default_path.as_str()];
        for path in paths {
            let content = std::fs::read_to_string(path).unwrap();
            assert!(
                content.lines().any(|l| l.trim() == BUILTIN_BASHRC_STAMP),
                "{path} not regenerated with current stamp"
            );
            assert!(
                content.contains("__tasty_title()"),
                "{path} missing __tasty_title"
            );
        }
    }

    // 현재 스탬프의 사용자 저장 결과는 덮어쓰지 않는다.
    #[cfg(windows)]
    #[test]
    fn ensure_compiled_bashrc_keeps_current_files() {
        let home = TmpHome::new();
        let tasty_path =
            tasty_bashrc_path_in(Some(home.path())).expect("injected home always resolves");
        std::fs::create_dir_all(std::path::Path::new(&tasty_path).parent().unwrap()).unwrap();
        let current = compose_tasty_mode_bashrc("# SENTINEL-user-content\n");
        std::fs::write(&tasty_path, &current).unwrap();

        ensure_compiled_bashrc_in(Some(home.path()));

        let content = std::fs::read_to_string(&tasty_path).unwrap();
        assert!(
            content.contains("# SENTINEL-user-content"),
            "current-stamped file must not be overwritten"
        );
    }

    // --rcfile이 적용되도록 비로그인 대화형 -i를 사용한다.
    #[cfg(not(windows))]
    #[test]
    fn unix_bash_effective_args_use_rcfile_and_interactive() {
        let home = TmpHome::new();
        let args = settings_with_shell("/bin/bash").effective_shell_args_in(Some(home.path()));
        assert_eq!(args.len(), 3);
        assert_eq!(args[0], "--rcfile");
        assert!(args[1].ends_with("bashrc.default"));
        assert_eq!(args[2], "-i");
    }

    #[cfg(not(windows))]
    #[test]
    fn unix_bash_effective_envs_are_empty() {
        // 홈이 필요 없는 분기는 None을 주입해 환경변수 조회를 피한다.
        assert!(
            settings_with_shell("/bin/bash")
                .effective_shell_envs_in(None)
                .is_empty()
        );
    }

    #[cfg(not(windows))]
    #[test]
    fn unix_zsh_effective_args_are_empty() {
        assert!(
            settings_with_shell("/bin/zsh")
                .effective_shell_args_in(None)
                .is_empty()
        );
    }

    #[cfg(not(windows))]
    #[test]
    fn unix_zsh_effective_envs_set_zdotdir() {
        let home = TmpHome::new();
        let envs = settings_with_shell("/bin/zsh").effective_shell_envs_in(Some(home.path()));
        let zdotdir = envs
            .iter()
            .find(|(k, _)| k == "ZDOTDIR")
            .map(|(_, v)| v.as_str())
            .expect("ZDOTDIR present");
        assert!(zdotdir.ends_with("zsh-integration"));
    }

    #[cfg(not(windows))]
    #[test]
    fn unix_other_shell_args_and_envs_are_empty() {
        let s = settings_with_shell("/usr/bin/fish");
        assert!(s.effective_shell_args_in(None).is_empty());
        assert!(s.effective_shell_envs_in(None).is_empty());
    }

    #[test]
    fn zsh_zshenv_contains_osc133_hooks_and_zdotdir_restore() {
        let compiled = compose_zsh_zshenv();
        assert!(compiled.contains("__tasty_osc133_precmd()"));
        assert!(compiled.contains("__tasty_osc133_preexec()"));
        assert!(compiled.contains("add-zsh-hook precmd __tasty_osc133_precmd"));
        assert!(compiled.contains("add-zsh-hook preexec __tasty_osc133_preexec"));
        assert!(compiled.contains("__TASTY_ORIG_ZDOTDIR_SET"));
        assert!(compiled.contains("source \"$__tasty_real_zdotdir/.zshenv\""));
    }

    #[test]
    fn zsh_zshenv_carries_version_stamp() {
        assert!(
            compose_zsh_zshenv()
                .lines()
                .any(|l| l.trim() == BUILTIN_ZSHENV_STAMP)
        );
    }

    #[test]
    fn ensure_compiled_zshenv_regenerates_stale_file() {
        let home = TmpHome::new();
        let path = tasty_zshenv_path_in(Some(home.path())).expect("injected home always resolves");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "# old wrapper without stamp\n").unwrap();

        ensure_compiled_zshenv_in(Some(home.path()));

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.lines().any(|l| l.trim() == BUILTIN_ZSHENV_STAMP));
        assert!(content.contains("__tasty_osc133_precmd()"));
    }

    /// 홈이 없으면 빈 경로로 대신하지 않는다.
    #[test]
    fn unresolved_home_resolves_to_none_not_an_empty_path() {
        let cwd = std::path::PathBuf::from("/some/cwd");
        assert_eq!(resolve_tasty_dir(None, Some(cwd.clone())), None);
        // 대조군 — 절대 루트는 그대로, 상대 루트는 cwd 기준 절대화.
        assert_eq!(
            resolve_tasty_dir(Some("/abs/root".into()), Some(cwd.clone())),
            Some(std::path::PathBuf::from("/abs/root"))
        );
        assert_eq!(
            resolve_tasty_dir(Some("rel".into()), Some(cwd.clone())),
            Some(cwd.join("rel"))
        );
        // cwd 마저 없으면 상대 루트를 절대화할 수 없다.
        assert_eq!(resolve_tasty_dir(Some("rel".into()), None), None);
    }

    /// 홈이 없으면 --rcfile을 전달하지 않는다.
    #[test]
    fn unresolved_home_emits_no_bash_rcfile_args() {
        let settings = settings_with_shell("/bin/bash");
        assert!(
            bash_rcfile_args_in(&settings, None).is_empty(),
            "홈 미해석이면 --rcfile 인자를 내지 않는다"
        );
        #[cfg(windows)]
        assert!(
            bash_rcfile_args_in(&settings_with_mode("tasty"), None).is_empty(),
            "tasty 모드도 마찬가지"
        );
    }

    /// 홈이 없으면 ZDOTDIR를 주입하지 않는다.
    #[test]
    fn unresolved_home_injects_no_zdotdir() {
        assert!(zsh_shell_envs_in(None).is_empty());
    }

    /// 홈이 없으면 CWD의 bashrc.user를 읽지 않는다.
    #[test]
    fn unresolved_home_loads_the_initial_user_bashrc_not_a_cwd_file() {
        assert_eq!(load_user_bashrc_in(None), INITIAL_USER_BASHRC);
    }

    /// 홈이 없으면 저장을 거절한다.
    #[test]
    fn unresolved_home_refuses_to_save_user_bashrc() {
        let err = save_user_bashrc_in(None, "# user\n").expect_err("저장을 거절해야 한다");
        assert!(
            err.contains("unresolved"),
            "실패 사유가 호출자에게 전달돼야 한다: {err}"
        );
    }

    /// 홈이 없을 때 CWD에 통합 파일을 만들지 않는다. 시작 전에 파일이 이미 있으면
    /// 잘못된 시험 전제이므로 삭제해 숨기지 않고 실패로 알린다.
    #[test]
    fn unresolved_home_writes_no_generated_files() {
        let _s = SERIAL.lock().unwrap_or_else(|p| p.into_inner());
        let cwd = std::env::current_dir().expect("cwd");
        let names = ["bashrc", "bashrc.default", "bashrc.user", "zsh-integration"];
        for n in names {
            assert!(
                !cwd.join(n).exists(),
                "{n} 이 이미 CWD 에 있다 — 앞선 실험이 남긴 오염이다. 이 테스트가 \
                 무엇을 단정하는지 무의미해지므로 지우고 다시 돌려라"
            );
        }

        ensure_compiled_bashrc_in(None);
        ensure_compiled_zshenv_in(None);

        for n in names {
            assert!(
                !cwd.join(n).exists(),
                "홈 미해석이면 프로세스 CWD 에 {n} 을 만들지 않는다"
            );
        }
    }

    // 경로 조회만으로 상대 홈의 절대화를 확인한다. 통합 파일 생성은 호출하지 않는다.
    #[test]
    fn relative_tasty_home_is_absolutized_for_child_processes() {
        // 패닉 때도 환경을 복원하고 다른 상대 홈 시험과 같은 락을 사용한다.
        let _home = RelativeHomeGuard::name("relative-tasty-home");

        let rc = tasty_bashrc_default_path().expect("relative home still resolves");
        let zdotdir = tasty_zsh_integration_dir().expect("relative home still resolves");

        let cwd = std::env::current_dir().expect("cwd");
        assert!(
            std::path::Path::new(&rc).is_absolute(),
            "--rcfile path must be absolute, got {rc}"
        );
        assert_eq!(
            std::path::Path::new(&rc),
            cwd.join("relative-tasty-home").join("bashrc.default")
        );
        assert!(
            zdotdir.is_absolute(),
            "ZDOTDIR must be absolute, got {}",
            zdotdir.display()
        );
        assert_eq!(
            zdotdir,
            cwd.join("relative-tasty-home").join("zsh-integration")
        );
    }

    /// 상대 TASTY_HOME의 설정·복원을 같은 SERIAL 락 안에서 수행한다.
    /// 절대 경로만 쓰면 해석 전후 차이를 검출하지 못해 상대 경로로 검사한다.
    struct RelativeHomeGuard {
        prev: Option<String>,
        /// 실제로 파일이 떨어질 임시 디렉토리(파일을 만드는 경로에서만 쓴다).
        _dir: Option<tempfile::TempDir>,
        /// 마지막 필드라 Drop::drop(env 복원) 뒤에 떨어져 복원이 락 안에서 난다.
        _lock: std::sync::MutexGuard<'static, ()>,
    }

    impl RelativeHomeGuard {
        fn set(
            rel: &std::path::Path,
            dir: Option<tempfile::TempDir>,
            lock: std::sync::MutexGuard<'static, ()>,
        ) -> Self {
            let prev = std::env::var("TASTY_HOME").ok();
            // SAFETY: 테스트 프로세스 단독 — SERIAL 락으로 병렬 간섭 차단.
            unsafe { std::env::set_var("TASTY_HOME", rel) };
            Self {
                prev,
                _dir: dir,
                _lock: lock,
            }
        }

        /// CWD 아래의 상대 이름. **파일을 만들지 않는 경로에서만** 쓴다 — 만들면
        /// 레포 워킹트리가 더러워진다.
        fn name(rel: &str) -> Self {
            let lock = SERIAL.lock().unwrap_or_else(|p| p.into_inner());
            Self::set(std::path::Path::new(rel), None, lock)
        }

        /// 임시 디렉토리를 가리키는 **상대** 경로(CWD 에서 `..` 로 거슬러 올라간다).
        /// 상대성은 유지하면서 생성 파일은 임시 디렉토리에 떨어뜨린다.
        fn temp() -> Self {
            // 락을 먼저 잡는다 — 아래 `current_dir()` 읽기까지 직렬화 범위에 넣는다.
            let lock = SERIAL.lock().unwrap_or_else(|p| p.into_inner());
            let dir = tempfile::tempdir().expect("tempdir");
            let cwd = std::env::current_dir().expect("cwd");
            let mut rel = std::path::PathBuf::new();
            for c in cwd.components() {
                if matches!(c, std::path::Component::Normal(_)) {
                    rel.push("..");
                }
            }
            for c in dir.path().components() {
                if let std::path::Component::Normal(seg) = c {
                    rel.push(seg);
                }
            }
            assert!(rel.is_relative(), "가드가 상대 경로를 만들어야 의미가 있다");
            Self::set(&rel, Some(dir), lock)
        }
    }

    impl Drop for RelativeHomeGuard {
        fn drop(&mut self) {
            match &self.prev {
                // SAFETY: 테스트 프로세스 단독 — SERIAL 락으로 병렬 간섭 차단.
                Some(v) => unsafe { std::env::set_var("TASTY_HOME", v) },
                // SAFETY: 상동.
                None => unsafe { std::env::remove_var("TASTY_HOME") },
            }
        }
    }

    fn bash_shell_path() -> String {
        if cfg!(windows) {
            "bash.exe"
        } else {
            "/bin/bash"
        }
        .to_string()
    }

    /// bash 인자가 호스트 cwd 기준으로 절대화한 루트를 사용하는지 확인한다.
    #[test]
    fn bash_rcfile_args_uses_the_resolved_root() {
        let _home = RelativeHomeGuard::name("relative-tasty-home");

        let settings = GeneralSettings {
            shell: bash_shell_path(),
            ..GeneralSettings::default()
        };
        let args = bash_rcfile_args_in(&settings, tasty_dir().as_deref());

        let rc = args
            .iter()
            .position(|a| a == "--rcfile")
            .and_then(|i| args.get(i + 1))
            .expect("--rcfile 인자");
        assert!(
            std::path::Path::new(rc).is_absolute(),
            "래퍼가 해석된 루트를 넘겨야 한다 — 상대 --rcfile 은 자식 셸의 CWD 로 \
             재해석된다, got {rc}"
        );
        assert!(
            rc.contains("relative-tasty-home"),
            "설정한 TASTY_HOME 아래를 가리켜야 한다, got {rc}"
        );
    }

    /// zsh 환경변수도 절대화한 루트를 사용하는지 확인한다. wrapper 파일은 임시 디렉터리에 만든다.
    #[test]
    fn effective_shell_envs_uses_the_resolved_root() {
        let _home = RelativeHomeGuard::temp();

        let settings = GeneralSettings {
            shell: "zsh".to_string(),
            ..GeneralSettings::default()
        };
        let envs = settings.effective_shell_envs();

        let zdotdir = envs
            .iter()
            .find(|(k, _)| k == "ZDOTDIR")
            .map(|(_, v)| v.as_str())
            .expect("ZDOTDIR");
        assert!(
            std::path::Path::new(zdotdir).is_absolute(),
            "래퍼가 해석된 루트를 넘겨야 한다 — 상대 ZDOTDIR 은 zsh 의 CWD 로 \
             재해석된다, got {zdotdir}"
        );
    }

    #[test]
    fn ensure_compiled_zshenv_keeps_current_file() {
        let home = TmpHome::new();
        let path = tasty_zshenv_path_in(Some(home.path())).expect("injected home always resolves");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        // 스탬프는 있지만 임의로 조작해 재생성되면 바로 드러나는 sentinel 을 심는다.
        let current = format!("{}\n# SENTINEL\n", BUILTIN_ZSHENV_STAMP);
        std::fs::write(&path, &current).unwrap();

        ensure_compiled_zshenv_in(Some(home.path()));

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(
            content.contains("# SENTINEL"),
            "current-stamped file must not be overwritten"
        );
    }
}
