//! 빌드타임 SVG → 벡터 베이크 (방식 B).
//!
//! `tasty-icons`(build-dependency, egui-free, 런타임 바이너리 크기 영향 0)의
//! `Icon.svg` 를 `usvg` 로 파싱해 서브패스별 폴리라인으로 평탄화하고,
//! `OUT_DIR/plugin_icons.rs` 에 `pub const <NAME>: &[&[[f32; 2]]]`(viewBox 0..24
//! 좌표) 상수를 생성한다. 런타임은 이 점배열을 그릴 크기로 스케일해
//! `egui::Shape::line` + `PathStroke` 로 그린다(텍스처 없음, DPI 독립).
//!
//! canonical 소스는 `tasty-icons` 크레이트 하나 — host/gallery 런타임 렌더와
//! **바이트 동일한 같은 `<svg>` 문자열**을 여기서 베이크한다. 아이콘을 추가하려면
//! `ICONS` 에 (상수명, `tasty_icons::<ICON>`) 쌍만 더한다.

use std::fmt::Write as _;
use std::path::Path;

use usvg::tiny_skia_path::PathSegment;
use usvg::{Options, TreeParsing};

/// (생성 상수명, canonical `tasty-icons` const). 툴바에서 쓰는 아이콘 subset.
const ICONS: &[(&str, tasty_icons::Icon)] = &[
    ("REFRESH", tasty_icons::REFRESH),
    ("CHEVRON_LEFT", tasty_icons::CHEVRON_LEFT),
    ("CHEVRON_RIGHT", tasty_icons::CHEVRON_RIGHT),
    ("EDIT", tasty_icons::EDIT),
    ("PLUS", tasty_icons::PLUS),
    ("FOLDER_OPEN", tasty_icons::FOLDER_OPEN),
    ("UNDO", tasty_icons::UNDO),
    ("REDO", tasty_icons::REDO),
];

/// 베지어 평탄화 허용 오차 (viewBox 24 단위, px). 작을수록 곡선이 매끄럽고 점이 많다.
/// 시각 품질은 Linux(gx10) 실렌더로 host `Icon` 과 대조해 확정한다.
const FLATTEN_TOLERANCE: f64 = 0.1;

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");

    let mut generated = String::from(
        "// @generated by build.rs (tasty-icons SVG bake) — do not edit.\n\
         /// 서브패스별 폴리라인. 좌표는 viewBox 0..24 절대좌표.\n",
    );

    for (const_name, icon) in ICONS {
        let tree = usvg::Tree::from_str(icon.svg, &Options::default())
            .unwrap_or_else(|e| panic!("failed to parse baked icon {const_name}: {e}"));

        let subpaths = flatten_tree(&tree);
        assert!(!subpaths.is_empty(), "no path geometry baked from {const_name}");

        write_const(&mut generated, const_name, &subpaths);
    }

    let out_path = Path::new(&out_dir).join("plugin_icons.rs");
    std::fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
    // 아이콘 소스 rerun 은 build-dep(tasty-icons) 재컴파일이 자동 트리거한다.
    println!("cargo:rerun-if-changed=build.rs");
}

/// 트리의 모든 Path 를 서브패스(폴리라인) 목록으로 평탄화. 좌표는 절대좌표
/// (usvg 가 transform 을 이미 적용 — `Path::data` 는 absolute coordinates).
fn flatten_tree(tree: &usvg::Tree) -> Vec<Vec<[f64; 2]>> {
    let mut subpaths: Vec<Vec<[f64; 2]>> = Vec::new();

    for node in tree.root.descendants() {
        let usvg::NodeKind::Path(ref path) = *node.borrow() else {
            continue;
        };
        let mut current: Vec<[f64; 2]> = Vec::new();
        for seg in path.data.segments() {
            match seg {
                PathSegment::MoveTo(p) => {
                    if current.len() >= 2 {
                        subpaths.push(std::mem::take(&mut current));
                    } else {
                        current.clear();
                    }
                    current.push([p.x as f64, p.y as f64]);
                }
                PathSegment::LineTo(p) => current.push([p.x as f64, p.y as f64]),
                PathSegment::QuadTo(p1, p2) => {
                    let p0 = *current.last().expect("QuadTo without a start point");
                    flatten_quad(
                        p0,
                        [p1.x as f64, p1.y as f64],
                        [p2.x as f64, p2.y as f64],
                        0,
                        &mut current,
                    );
                }
                PathSegment::CubicTo(p1, p2, p3) => {
                    let p0 = *current.last().expect("CubicTo without a start point");
                    flatten_cubic(
                        p0,
                        [p1.x as f64, p1.y as f64],
                        [p2.x as f64, p2.y as f64],
                        [p3.x as f64, p3.y as f64],
                        0,
                        &mut current,
                    );
                }
                PathSegment::Close => {
                    if let Some(&first) = current.first() {
                        current.push(first);
                    }
                }
            }
        }
        if current.len() >= 2 {
            subpaths.push(current);
        }
    }

    subpaths
}

const MAX_SUBDIV_DEPTH: u8 = 16;

fn mid(a: [f64; 2], b: [f64; 2]) -> [f64; 2] {
    [(a[0] + b[0]) * 0.5, (a[1] + b[1]) * 0.5]
}

/// 점 `p` 와 선분 `a`-`b` 사이 수직 거리.
fn dist_point_line(p: [f64; 2], a: [f64; 2], b: [f64; 2]) -> f64 {
    let (dx, dy) = (b[0] - a[0], b[1] - a[1]);
    let len2 = dx * dx + dy * dy;
    if len2 <= f64::EPSILON {
        let (ex, ey) = (p[0] - a[0], p[1] - a[1]);
        return (ex * ex + ey * ey).sqrt();
    }
    let cross = (p[0] - a[0]) * dy - (p[1] - a[1]) * dx;
    cross.abs() / len2.sqrt()
}

/// 3차 베지어를 de Casteljau 재귀 분할로 평탄화 (끝점 p3 는 포함, 시작점 p0 은 이미
/// `out` 에 있다고 가정).
fn flatten_cubic(
    p0: [f64; 2],
    p1: [f64; 2],
    p2: [f64; 2],
    p3: [f64; 2],
    depth: u8,
    out: &mut Vec<[f64; 2]>,
) {
    let flat = dist_point_line(p1, p0, p3).max(dist_point_line(p2, p0, p3)) <= FLATTEN_TOLERANCE;
    if flat || depth >= MAX_SUBDIV_DEPTH {
        out.push(p3);
        return;
    }
    let p01 = mid(p0, p1);
    let p12 = mid(p1, p2);
    let p23 = mid(p2, p3);
    let p012 = mid(p01, p12);
    let p123 = mid(p12, p23);
    let p0123 = mid(p012, p123);
    flatten_cubic(p0, p01, p012, p0123, depth + 1, out);
    flatten_cubic(p0123, p123, p23, p3, depth + 1, out);
}

/// 2차 베지어를 de Casteljau 재귀 분할로 평탄화.
fn flatten_quad(p0: [f64; 2], p1: [f64; 2], p2: [f64; 2], depth: u8, out: &mut Vec<[f64; 2]>) {
    let flat = dist_point_line(p1, p0, p2) <= FLATTEN_TOLERANCE;
    if flat || depth >= MAX_SUBDIV_DEPTH {
        out.push(p2);
        return;
    }
    let p01 = mid(p0, p1);
    let p12 = mid(p1, p2);
    let p012 = mid(p01, p12);
    flatten_quad(p0, p01, p012, depth + 1, out);
    flatten_quad(p012, p12, p2, depth + 1, out);
}

fn write_const(out: &mut String, name: &str, subpaths: &[Vec<[f64; 2]>]) {
    write!(out, "pub const {name}: &[&[[f32; 2]]] = &[").expect("write const header");
    for sub in subpaths {
        out.push_str("\n    &[");
        for p in sub {
            write!(out, "[{:.4}, {:.4}], ", p[0], p[1]).expect("write point");
        }
        out.push_str("],");
    }
    out.push_str("\n];\n");
}
