//! 모든 popup의 `PopupDef` 목록. 새 popup을 추가하려면 이 파일에 한 항목만 추가.

use std::sync::OnceLock;

use super::{DragHandle, PopupDef, PopupScope, PopupState};

/// 헤드리스 패널 팝업(port_scanner / remote_tool)의 전용 드래그 띠.
///
/// 헤더 **좌측 절반**(아이콘 + 제목 라벨만 있는 영역)을 핸들로 선언한다. 우측의
/// 검색 입력 / Refresh / Close 버튼과는 겹치지 않으므로 위젯 우선 중재 없이 안전하다
/// (승인된 "전용 핸들 띠" 방식). 높이는 타이틀바 토큰(`title_bar_height`)을 재사용해
/// 헤더 중앙의 라벨을 덮는다. 테두리 리사이즈 밴드(좌/상단 수 px)는 우선순위가
/// 높아 그 부분은 리사이즈로 동작한다.
fn panel_header_drag_strip(s: &PopupState) -> egui::Rect {
    egui::Rect::from_min_size(s.pos, egui::vec2(s.size.x * 0.5, super::title_bar_height()))
}

/// 프로세스 수명 내내 살아있는 정적 popup 정의 목록.
pub fn all_defs() -> &'static [PopupDef] {
    static DEFS: OnceLock<Vec<PopupDef>> = OnceLock::new();
    DEFS.get_or_init(|| {
        vec![
            PopupDef {
                id: "notifications",
                title_key: "notification_panel.window_title",
                title_fn: None,
                default_size: egui::vec2(350.0, 400.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: true,
                min_size: Some(egui::vec2(280.0, 200.0)),
                draw_fn: crate::adapters::ui::notification::draw_notification_popup,
            },
            PopupDef {
                id: "convert_surface",
                title_key: "convert_popup.title",
                title_fn: None,
                default_size: super::convert::convert_popup_default_size(),
                sizer: Some(super::convert::convert_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: true,
                min_size: Some(egui::vec2(300.0, 200.0)),
                draw_fn: super::convert::draw_convert_popup,
            },
            PopupDef {
                id: "markdown_open",
                title_key: "dialog.markdown.title",
                title_fn: None,
                default_size: egui::vec2(360.0, 200.0),
                sizer: Some(super::file_open::markdown_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::file_open::draw_markdown_open_popup,
            },
            PopupDef {
                id: "rename",
                title_key: "rename_dialog.tab_heading",
                title_fn: Some(crate::adapters::ui::dialog::rename_popup_title),
                default_size: crate::adapters::ui::dialog::rename_popup_default_size(),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::dialog::draw_rename_popup,
            },
            PopupDef {
                id: "search_bar",
                title_key: "search.placeholder",
                title_fn: None,
                default_size: egui::vec2(360.0, 28.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: true,
                sticky_focus: false,
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::search_bar::draw_search_bar,
            },
            PopupDef {
                id: crate::adapters::ui::info_modal::INFO_MODAL_ID,
                title_key: "button.ok",
                title_fn: Some(crate::adapters::ui::info_modal::info_modal_title),
                default_size: egui::vec2(440.0, 160.0),
                sizer: Some(crate::adapters::ui::info_modal::info_modal_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::info_modal::draw_info_modal,
            },
            PopupDef {
                id: super::approval::APPROVAL_POPUP_ID,
                title_key: "approval.popup.title",
                title_fn: Some(super::approval::approval_popup_title),
                default_size: egui::vec2(480.0, 240.0),
                sizer: Some(super::approval::approval_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: true,
                min_size: Some(egui::vec2(400.0, 200.0)),
                draw_fn: super::approval::draw_approval_popup,
            },
            PopupDef {
                id: super::file_handler_picker::PICKER_POPUP_ID,
                title_key: "file_handler.picker.title",
                title_fn: Some(super::file_handler_picker::picker_title),
                default_size: egui::vec2(480.0, 320.0),
                sizer: Some(super::file_handler_picker::picker_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: true,
                min_size: Some(egui::vec2(360.0, 240.0)),
                draw_fn: super::file_handler_picker::draw_file_handler_picker,
            },
            PopupDef {
                id: super::port_scanner::PORT_SCANNER_POPUP_ID,
                title_key: "port_scanner.heading",
                title_fn: None,
                default_size: egui::vec2(660.0, 520.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 타이틀바 없는 패널 — 헤더 좌측 전용 띠를 드래그 핸들로 선언.
                drag_handle: DragHandle::Region(panel_header_drag_strip),
                resizable: true,
                min_size: Some(egui::vec2(480.0, 320.0)),
                draw_fn: super::port_scanner::draw_port_scanner_popup,
            },
            PopupDef {
                id: super::command_palette::COMMAND_PALETTE_POPUP_ID,
                title_key: "command_palette.heading",
                title_fn: None,
                // 디자인 콘텐츠 높이 ≈ search(49) + list(maxH320 + pad12=332) + footer(31)
                // = 412. design-parity: list 가 320 꽉 차는 실사용 기준 높이.
                default_size: egui::vec2(540.0, 412.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: true,
                // 중앙 정렬 팔레트 — 이동/리사이즈 비활성.
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: super::command_palette::draw_command_palette_popup,
            },
            PopupDef {
                id: super::remote_tool::REMOTE_TOOL_POPUP_ID,
                title_key: "remote_tool.heading",
                title_fn: None,
                default_size: egui::vec2(520.0, 460.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: true,
                sticky_focus: false,
                // 타이틀바 없는 패널 — 헤더 좌측 전용 띠를 드래그 핸들로 선언.
                drag_handle: DragHandle::Region(panel_header_drag_strip),
                resizable: true,
                min_size: Some(egui::vec2(400.0, 300.0)),
                draw_fn: super::remote_tool::draw_remote_tool_popup,
            },
            PopupDef {
                id: super::preset_apply::APPLY_WORKSPACE_POPUP_ID,
                title_key: "preset.popup.apply_workspace_title",
                title_fn: None,
                default_size: egui::vec2(360.0, 320.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::preset_apply::draw_apply_workspace_popup,
            },
            PopupDef {
                id: super::preset_apply::APPLY_TAB_POPUP_ID,
                title_key: "preset.popup.apply_tab_title",
                title_fn: None,
                default_size: egui::vec2(360.0, 320.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::preset_apply::draw_apply_tab_popup,
            },
            PopupDef {
                id: super::preset_apply::APPLY_PANE_POPUP_ID,
                title_key: "preset.popup.apply_pane_title",
                title_fn: None,
                default_size: egui::vec2(360.0, 320.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::preset_apply::draw_apply_pane_popup,
            },
            PopupDef {
                id: "tools_menu",
                title_key: "tools_menu.title",
                title_fn: None,
                default_size: crate::adapters::ui::tools_menu::tools_menu_default_size(),
                sizer: Some(crate::adapters::ui::tools_menu::tools_menu_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 컨텍스트 메뉴 스타일 — 이동/리사이즈 비활성.
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::tools_menu::draw_tools_menu,
            },
        ]
    })
}

/// id로 정의 하나를 찾는다.
pub fn find(id: &str) -> Option<&'static PopupDef> {
    all_defs().iter().find(|d| d.id == id)
}
