//! 모든 popup의 `PopupDef` 목록. 새 popup을 추가하려면 이 파일에 한 항목만 추가.

use std::sync::OnceLock;

use super::{DragHandle, PopupDef, PopupScope, PopupState};

/// 헤드리스 패널 팝업(port_scanner / remote_tool)의 헤더 드래그 띠 — **폴백**.
///
/// 평상시 이 두 팝업은 뷰가 `report_header_drag_rect` 로 보고한 **실측 헤더 전체**
/// rect 를 hit-test 에 쓴다(`PopupState::effective_drag_handle_rect`). 이 좁은 띠는
/// **open 첫 프레임**(아직 보고 전)에만 잠깐 쓰이는 폴백이다. 헤더 좌측 절반 ×
/// 타이틀바 높이만 덮으므로 그 프레임 한정 좌측 상단만 드래그 가능하나, 다음
/// 프레임부터 보고 rect 로 대체돼 헤더 전체가 이동 영역이 된다. 위젯 우선 중재
/// (`is_using_pointer()`)로 겹친 입력 클릭은 항상 우선된다.
fn panel_header_drag_strip(s: &PopupState) -> egui::Rect {
    egui::Rect::from_min_size(s.pos, egui::vec2(s.size.x * 0.5, super::title_bar_height()))
}

/// 프로세스 수명 내내 살아있는 정적 popup 정의 목록.
pub fn all_defs() -> &'static [PopupDef] {
    static DEFS: OnceLock<Vec<PopupDef>> = OnceLock::new();
    DEFS.get_or_init(|| {
        vec![
            PopupDef {
                id: "notifications",
                title_key: "notification_panel.window_title",
                title_fn: None,
                default_size: egui::vec2(350.0, 400.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::notification::draw_notification_popup,
                on_close: None,
            },
            PopupDef {
                id: "convert_surface",
                title_key: "convert_popup.title",
                title_fn: None,
                default_size: super::convert::convert_popup_default_size(),
                sizer: Some(super::convert::convert_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::convert::draw_convert_popup,
                on_close: Some(super::convert::on_close_convert_popup),
            },
            PopupDef {
                id: "script_changed_confirm",
                title_key: "script.confirm.title",
                title_fn: None,
                default_size: egui::vec2(360.0, 150.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::script_confirm::draw_script_confirm_popup,
                on_close: None,
            },
            PopupDef {
                id: "rename",
                title_key: "rename_dialog.tab_heading",
                title_fn: Some(crate::adapters::ui::dialog::rename_popup_title),
                default_size: crate::adapters::ui::dialog::rename_popup_default_size(),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::dialog::draw_rename_popup,
                on_close: Some(crate::adapters::ui::dialog::on_close_rename_popup),
            },
            PopupDef {
                id: "search_bar",
                title_key: "search.placeholder",
                title_fn: None,
                default_size: egui::vec2(360.0, 28.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: true,
                sticky_focus: false,
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::search_bar::draw_search_bar,
                on_close: None,
            },
            PopupDef {
                id: crate::adapters::ui::info_modal::INFO_MODAL_ID,
                title_key: "button.ok",
                title_fn: Some(crate::adapters::ui::info_modal::info_modal_title),
                default_size: egui::vec2(440.0, 160.0),
                sizer: Some(crate::adapters::ui::info_modal::info_modal_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::info_modal::draw_info_modal,
                on_close: Some(crate::adapters::ui::info_modal::on_close_info_modal),
            },
            PopupDef {
                id: super::approval::APPROVAL_POPUP_ID,
                title_key: "approval.popup.title",
                title_fn: Some(super::approval::approval_popup_title),
                default_size: egui::vec2(480.0, 240.0),
                sizer: Some(super::approval::approval_popup_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::approval::draw_approval_popup,
                on_close: Some(super::approval::on_close_approval_popup),
            },
            PopupDef {
                id: super::file_handler_picker::PICKER_POPUP_ID,
                title_key: "file_handler.picker.title",
                title_fn: Some(super::file_handler_picker::picker_title),
                default_size: egui::vec2(480.0, 320.0),
                sizer: Some(super::file_handler_picker::picker_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::file_handler_picker::draw_file_handler_picker,
                on_close: Some(super::file_handler_picker::on_close_file_handler_picker),
            },
            PopupDef {
                id: super::file_picker::FILE_PICKER_POPUP_ID,
                title_key: "filepicker.title",
                title_fn: None,
                default_size: egui::vec2(640.0, 480.0),
                sizer: Some(super::file_picker::picker_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::file_picker::draw_file_picker,
                on_close: Some(super::file_picker::on_close_file_picker),
            },
            PopupDef {
                id: super::port_scanner::PORT_SCANNER_POPUP_ID,
                title_key: "port_scanner.heading",
                title_fn: None,
                default_size: egui::vec2(660.0, 520.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 타이틀바 없는 패널 — 헤더 좌측 전용 띠를 드래그 핸들로 선언.
                drag_handle: DragHandle::Region(panel_header_drag_strip),
                resizable: true,
                min_size: Some(egui::vec2(480.0, 320.0)),
                draw_fn: super::port_scanner::draw_port_scanner_popup,
                // 바깥 클릭(headless + close_on_outside_click=true)으로 닫으면
                // `PortScanState::Loading{rx}`/`Ready{rows}` 가 그대로 남는다 — 의도적
                // 결정: 재오픈 시 이전 스캔 결과를 그대로 보여준다(초기화하지 않음).
                // Close 버튼(draw_fn 내부)만 명시적으로 `Idle` 로 되돌린다.
                on_close: None,
            },
            PopupDef {
                id: super::command_palette::COMMAND_PALETTE_POPUP_ID,
                title_key: "command_palette.heading",
                title_fn: None,
                // 디자인 콘텐츠 높이 ≈ search(49) + list(maxH320 + pad12=332) + footer(31)
                // = 412. design-parity: list 가 320 꽉 차는 실사용 기준 높이.
                default_size: egui::vec2(540.0, 412.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: true,
                // 중앙 정렬 팔레트 — 이동/리사이즈 비활성.
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: super::command_palette::draw_command_palette_popup,
                on_close: None,
            },
            PopupDef {
                id: super::remote_tool::REMOTE_TOOL_POPUP_ID,
                title_key: "remote_tool.heading",
                title_fn: None,
                default_size: egui::vec2(520.0, 460.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: true,
                sticky_focus: false,
                // 타이틀바 없는 패널 — 헤더 좌측 전용 띠를 드래그 핸들로 선언.
                drag_handle: DragHandle::Region(panel_header_drag_strip),
                resizable: true,
                min_size: Some(egui::vec2(420.0, 320.0)),
                draw_fn: super::remote_tool::draw_remote_tool_popup,
                on_close: None,
            },
            PopupDef {
                id: super::remote_attach::REMOTE_ATTACH_POPUP_ID,
                title_key: "remote_attach.heading",
                title_fn: None,
                default_size: egui::vec2(680.0, 460.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: true,
                sticky_focus: false,
                // 모달 성격 — 중앙 정렬, 이동/리사이즈 없음(디자인 Scrim 위 고정 프레임).
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: super::remote_attach::draw_remote_attach_popup,
                on_close: None,
            },
            // (09) 원격 전송 진행 — scrim 중앙 headless, close_on_outside_click=false
            // (전송 중 실수 dismiss 방지), 모든 행 완료 시 draw_fn 이 self-close.
            PopupDef {
                id: super::transfer::TRANSFER_PROGRESS_POPUP_ID,
                title_key: "transfer.progress.title",
                title_fn: None,
                default_size: egui::vec2(400.0, 180.0),
                sizer: Some(super::transfer::transfer_progress_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: false,
                headless: true,
                sticky_focus: false,
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: super::transfer::draw_transfer_progress,
                on_close: Some(super::transfer::on_close_transfer_progress),
            },
            // (09) 원격 전송 실패 — scrim 중앙 headless, 기본 dismiss(Esc/scrim). Retry 는
            // 전송 중 실패만(draw_fn 이 판정). danger-fill 버튼 금지.
            PopupDef {
                id: super::transfer::TRANSFER_ERROR_POPUP_ID,
                title_key: "transfer.error.title",
                title_fn: None,
                default_size: egui::vec2(400.0, 200.0),
                sizer: Some(super::transfer::transfer_error_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: super::transfer::draw_transfer_error,
                on_close: Some(super::transfer::on_close_transfer_error),
            },
            PopupDef {
                id: super::preset_apply::APPLY_WORKSPACE_POPUP_ID,
                title_key: "preset.popup.apply_workspace_title",
                title_fn: None,
                default_size: egui::vec2(360.0, 320.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::preset_apply::draw_apply_workspace_popup,
                on_close: Some(super::preset_apply::on_close_apply_preset_popup),
            },
            PopupDef {
                id: super::preset_apply::APPLY_TAB_POPUP_ID,
                title_key: "preset.popup.apply_tab_title",
                title_fn: None,
                default_size: egui::vec2(360.0, 320.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::preset_apply::draw_apply_tab_popup,
                on_close: Some(super::preset_apply::on_close_apply_preset_popup),
            },
            PopupDef {
                id: super::preset_apply::APPLY_PANE_POPUP_ID,
                title_key: "preset.popup.apply_pane_title",
                title_fn: None,
                default_size: egui::vec2(360.0, 320.0),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: false,
                sticky_focus: false,
                drag_handle: DragHandle::TitleBar,
                resizable: false,
                min_size: None,
                draw_fn: super::preset_apply::draw_apply_pane_popup,
                on_close: Some(super::preset_apply::on_close_apply_preset_popup),
            },
            PopupDef {
                id: "tools_menu",
                title_key: "tools_menu.title",
                title_fn: None,
                default_size: crate::adapters::ui::tools_menu::tools_menu_default_size(),
                sizer: Some(crate::adapters::ui::tools_menu::tools_menu_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 컨텍스트 메뉴 스타일 — 이동/리사이즈 비활성.
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::tools_menu::draw_tools_menu,
                on_close: None,
            },
            PopupDef {
                id: crate::adapters::ui::mouse_capture_menu::MOUSE_CAPTURE_BANNER_MENU_POPUP_ID,
                title_key: "popup.mouse_capture_banner_menu.title",
                title_fn: None,
                default_size: crate::adapters::ui::mouse_capture_menu::menu_default_size(),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 마우스 캡처 배너 "더보기" 컨텍스트 메뉴 — tools_menu 와 동일하게
                // 이동/리사이즈 비활성.
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::mouse_capture_menu::draw_menu,
                on_close: None,
            },
            PopupDef {
                id: super::confirm_delete_category::CONFIRM_DELETE_CATEGORY_POPUP_ID,
                title_key: "workspace_category.delete_confirm_title",
                title_fn: Some(super::confirm_delete_category::confirm_delete_category_title),
                default_size: egui::vec2(380.0, 150.0),
                sizer: Some(super::confirm_delete_category::confirm_delete_category_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 소형 모달 — 이동/리사이즈 비활성, 중앙 정렬로 연다.
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: super::confirm_delete_category::draw_confirm_delete_category,
                on_close: Some(super::confirm_delete_category::on_close_confirm_delete_category),
            },
            PopupDef {
                id: crate::adapters::ui::tutorial::topic_popup::TUTORIAL_TOPICS_POPUP_ID,
                title_key: "tutorial.popup_title",
                title_fn: None,
                default_size:
                    crate::adapters::ui::tutorial::topic_popup::tutorial_topics_default_size(),
                sizer: None,
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 중앙 정렬 모달 — 이동/리사이즈 비활성(디자인 CenteredFocused).
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: crate::adapters::ui::tutorial::topic_popup::draw_tutorial_topics_popup,
                on_close: None,
            },
            PopupDef {
                id: super::rail_category::RAIL_CATEGORY_POPUP_ID,
                title_key: "workspace_category.heading",
                title_fn: None,
                default_size: super::rail_category::rail_category_default_size(),
                sizer: Some(super::rail_category::rail_category_sizer),
                default_scope: PopupScope::Window,
                close_on_outside_click: true,
                headless: true,
                sticky_focus: false,
                // 컨텍스트 메뉴 스타일 — 이동/리사이즈 비활성 (레일 버튼 우측 앵커).
                drag_handle: DragHandle::None,
                resizable: false,
                min_size: None,
                draw_fn: super::rail_category::draw_rail_category_popup,
                on_close: Some(super::rail_category::on_close_rail_category_popup),
            },
        ]
    })
}

/// id로 정의 하나를 찾는다.
pub fn find(id: &str) -> Option<&'static PopupDef> {
    all_defs().iter().find(|d| d.id == id)
}
